### ISSUE TITLE
wrong coefficients in scatter glare correction example

### ISSUE THREAD

**Issue by PHU-medPhoton** [RTKConsortium/RTK#101]
Hi Simon.

I just saw that in your scatter glare corretion example "rtkscatterglarecorrection.cxx" there are two coefficients configured (lines 78 and 79). I guess you wanted to configure the coefficients as described by Poludniowski but the b3 coefficient is wrong (106.244f instead of 10.6244f). This produces huge artefacts and therfore could insecure other users.

Best,
Philipp Huber 
medPhoton

**Comment by sbrousmiche** [comment]
Hi Philipp,

Thanks for your remark.

We are actually not using the same units as in the reference paper for b3.
I agree this should be fixed for clarity.

Nevertheless, these are only default values. As the parameters are
system-dependent, I suggest we simply remove them no to confuse anyone.

Best Regards
Sébastien

**Comment by SimonRit** [comment]
Hi,
Thanks for your answer Sébastien (it's his filter, not mine!). A better solution would therefore to set them to irrelevant defaults (e.g., itk::NumericTraits<float>::max()) and issue an error if they are not set prior to their use?
Simon

**Comment by SimonRit** [comment]
Fixed with a87ae69
