### ISSUE TITLE
Warnings in VS2015 for dllimport / export

### ISSUE THREAD

**Issue by dkuegler** [RTKConsortium/RTK#142]
I get a bunch of DLLimport / DLLexport warnings like this:

6>G:/gitdev/lib/rtk/code/rtkCudaFFTConvolutionImageFilter.cu(196): warning : dllexport/dllimport conflict with "CUDA_padding"
6>  g:\gitdev\lib\rtk\code\rtkCudaFFTConvolutionImageFilter.hcu(33): here; dllexport assumed

This is for current RTK and VS 2015.

Cheers
David

**Comment by SimonRit** [comment]
Seems to be fixed now with commit 835ce69.
