### ISSUE TITLE
Auto Calibration Code?

### ISSUE THREAD

**Issue by daveycrocket** [RTKConsortium/RTK#149]
Sorry to ask it as an issue. I wasn't sure how to reach you.

I've been trying to find code for auto calibration of CT cone beam geometries. Does this library have such code or do you know of any available code out there? I was trying to read through your paper and a couple others that do auto calibration without a phantom, but I'm having a very hard time interpreting all the words into how the algorithm works and then write the code.

**Comment by SimonRit** [comment]
We have not made this code at this time. This is certainly not an RTK issue and I'm closing this issue.
