### ISSUE TITLE
unable to build SimpleRTK pthread.h not found

### ISSUE THREAD

**Issue by EmmanuelleRicher** [RTKConsortium/RTK#181]
Hi, 
I'm trying to use SimpleRTK on python. After generating it on CMake and building it on Visual Studio 14 2015, I have only one project that does not build, the SimpleRTK one. It gives me the following error:

1>------ Build started: Project: SuperBuildSimpleRTKSourceReal, Configuration: Debug x64 ------
2>------ Build started: Project: rtkData, Configuration: Debug x64 ------
3>------ Skipped Build: Project: Continuous, Configuration: Debug x64 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Build: Project: Experimental, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Build: Project: Nightly, Configuration: Debug x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Build: Project: NightlyMemoryCheck, Configuration: Debug x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Build: Project: RUN_TESTS, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
8>------ Build started: Project: rtkheadertest, Configuration: Debug x64 ------
1>  Generating C:/Users/admin/Desktop/RTK_Bin/ExternalData/.ExternalSource/lua-5.1.5.tar.gz
8>  rtkheadertest.cxx
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/2e115fe26e435e33b0d5c022e4490567"
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/2e115fe26e435e33b0d5c022e4490567"
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/2e115fe26e435e33b0d5c022e4490567"
1>  Generating C:/Users/admin/Desktop/RTK_Bin/ExternalData/.ExternalSource/swigwin-3.0.10.zip
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/f229724fe856aa78df6128ecfefe6e0a"
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/f229724fe856aa78df6128ecfefe6e0a"
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/f229724fe856aa78df6128ecfefe6e0a"
1>  Generating C:/Users/admin/Desktop/RTK_Bin/ExternalData/.ExternalSource/gtest-1.7.0.zip
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/2d6ec8ccdf5c46b05ba54a9fd1d130d7"
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/2d6ec8ccdf5c46b05ba54a9fd1d130d7"
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/2d6ec8ccdf5c46b05ba54a9fd1d130d7"
1>  Generating C:/Users/admin/Desktop/RTK_Bin/ExternalData/.ExternalSource/virtualenv-15.0.2.tar.gz
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/0ed59863994daf1292827ffdbba80a63"
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/0ed59863994daf1292827ffdbba80a63"
1>  -- Found object: "C:/Users/admin/Desktop/RTK_Bin/ExternalData/Objects/MD5/0ed59863994daf1292827ffdbba80a63"
9>------ Build started: Project: virtualenv, Configuration: Debug x64 ------
10>------ Build started: Project: GTest, Configuration: Debug x64 ------
11>------ Build started: Project: Swig, Configuration: Debug x64 ------
12>------ Build started: Project: Lua, Configuration: Debug x64 ------
13>------ Build started: Project: SimpleRTK, Configuration: Debug x64 ------
13>  Creating directories for 'SimpleRTK'
13>  Building Custom Rule C:/Users/admin/Desktop/RTK-1.4.0/CMakeLists.txt
13>  CMake does not need to re-run because C:/Users/admin/Desktop/RTK_Bin/CMakeFiles/generate.stamp is up-to-date.
13>  No download step for 'SimpleRTK'
13>  No update step for 'SimpleRTK'
13>  No patch step for 'SimpleRTK'
13>  Performing configure step for 'SimpleRTK'
13>  Not searching for unused variables given on the command line.
13>  loading initial cache file C:/Users/admin/Desktop/RTK_Bin/SimpleRTK-build/CMakeCacheInit.txt
13>  -- Selecting Windows SDK version  to target Windows 10.0.16299.
13>  CMake Error at CMake/srtkSourceVersion.cmake:38 (include):
13>    include could not find load file:
13>
13>      C:/Users/admin/Desktop/RTK-1.4.0/utilities/SimpleRTK/CMake/srtkSourceVersionVars.cmake
13>  Call Stack (most recent call first):
13>    Version.cmake:17 (include)
13>    CMakeLists.txt:25 (include)
13>
13>
13>  -- Building SimpleRTK version "1.0.0-gGITDIR-NOTFOUND"
13>  -- Checking if c++11 is required...
13>  -- Checking if c++11 is required... NO
13>  -- Found PythonLibs: optimized;optimized;optimized;C:/Anaconda3/libs/python36.lib;optimized;debug;optimized;C:/Anaconda3/libs/python36_d.lib;debug;C:/Anaconda3/libs/python36_d.lib (found suitable exact version "3.6.1")
13>  -- Found the following C# .NET versions: v4.0.30319, v3.5, v2.0.50727
13>  -- Processing json files...
13>  -- Processing json files...done
13>  CMake Deprecation Warning at Wrapping/Python/CMakeLists.txt:12 (cmake_policy):
13>    The OLD behavior for policy CMP0026 will be removed from a future version
13>    of CMake.
13>
13>    The cmake-policies(7) manual explains that the OLD behaviors of all
13>    policies are deprecated and that a policy should be set to OLD only under
13>    specific short-term circumstances.  Projects should be ported to the NEW
13>    behavior and not rely on setting a policy to OLD.
13>
13>
8>  rtkheadertest.vcxproj -> C:\Users\admin\Desktop\RTK_Bin\bin\Debug\rtkheadertest.exe
8>  rtkheadertest.vcxproj -> C:/Users/admin/Desktop/RTK_Bin/bin/Debug/rtkheadertest.pdb (Full PDB)
13>  -- Found PythonLibs: optimized;optimized;optimized;optimized;optimized;optimized;optimized;C:/Anaconda3/libs/python36.lib;optimized;optimized;optimized;debug;optimized;optimized;optimized;C:/Anaconda3/libs/python36_d.lib;optimized;debug;optimized;C:/Anaconda3/libs/python36_d.lib;debug;C:/Anaconda3/libs/python36_d.lib (found version "3.6.1")
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier "debug"
13>    instead of a library name.  The first specifier will be ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "debug" is followed by specifier "optimized"
13>    instead of a library name.  The first specifier will be ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier
13>    "optimized" instead of a library name.  The first specifier will be
13>    ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "optimized" is followed by specifier "debug"
13>    instead of a library name.  The first specifier will be ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  CMake Warning (dev) at CMake/srtkTargetLinkLibrariesWithDynamicLookup.cmake:87 (target_link_libraries):
13>    Link library type specifier "debug" is followed by specifier "optimized"
13>    instead of a library name.  The first specifier will be ignored.
13>  Call Stack (most recent call first):
13>    Wrapping/Python/CMakeLists.txt:52 (srtk_target_link_libraries_with_dynamic_lookup)
13>  This warning is for project developers.  Use -Wno-dev to suppress it.
13>
13>  -- Not using SimpleRTK's virtualenv for distribution!
13>
13>  Using unknown versions of pip, setuptools and/or wheel packages/
13>  -- Configuring incomplete, errors occurred!
13>  See also "C:/Users/admin/Desktop/RTK_Bin/SimpleRTK-build/CMakeFiles/CMakeOutput.log".
13>  See also "C:/Users/admin/Desktop/RTK_Bin/SimpleRTK-build/CMakeFiles/CMakeError.log".
13>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
14>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
14>Project not selected to build for this solution configuration 
========== Build: 7 succeeded, 1 failed, 163 up-to-date, 6 skipped ==========

I am using CMake 3.11.1, Visual Studio (Enterprise) 14 2015 and Cuda ToolKit 9.1 and I downloaded the 4.13.0 release of ITK and the 1.4.0 release of RTK.
Can somebody help to find what it is that I'm doing wrong? 

Thank you

**Comment by SimonRit** [comment]
I'm not sure the title matches the problem I see in your log. I think the problem is
13> CMake Error at CMake/srtkSourceVersion.cmake:38 (include):
13> include could not find load file:
@djboersma report the problem in  #152. Since we are fading out of SimpleRTK and building new wrappings, we won't fix the problem. The solution is to build from a git clone instead of the zip sources. Sorry for the inconvenience.
With the new wrappings, we will offer pre-compiled Python packages that can be installed with pip.

**Comment by EmmanuelleRicher** [comment]
Thank you!
