### ISSUE TITLE
reconstruction of Shepp Logan phantom 

### ISSUE THREAD

**Issue by EmmanuelleRicher** [RTKConsortium/RTK#192]
Hi, 

I am currently working on reconstructing cone beam projections made from the shepp logan phantom. I am using Simple RTK on PyCharm. I am able to reconstruct it but the results are not what I expected. 

My shepp logan data consists of 500 projections of 256 x 256 (19 464 444.72 um x 19 464 444.72 um x 38 016 493.60 um) 
Here is my code used to the reconstruction, it is basically the FirstReconstruction code (kind of but a little modified). 

ndaData  # contains my projection data as a ndarray 

# Generate a geometry
numberOfProjections = 500
self.geometry = srtk.ThreeDCircularProjectionGeometry()
self.sdd = 20000 # source to detector distance in mm
self.sid = 10000 # source to isocenter distance in mm
anglemin = 0  # first angle
anglemax = 360  # last angle
isox = 0
isoy = 0
outangle =0
inangle = 0
srcx = 0
srcy = 0
for noProj in range(0, numberOfProjections):
      angle = anglemin + noProj * anglemax / numberOfProjections
      self.geometry.AddProjection(self.sid, self.sdd, angle, isox, isoy, outangle, inangle, srcx, srcy)

 # Convert to a SimpleRTK image
srtkData = srtk.GetImageFromArray(ndaData)
uvSize = srtkData.GetSize()
spacing = (76.032, 76.032, 76.032)  # projection spacing in mm 
origin = [-0.5*spacing[0]*(uvSize[0]-1), -0.5*spacing[1]*(uvSize[1]-1), 0]  # centered
srtkData.SetSpacing(spacing)
srtkData.SetOrigin(origin)

constantImageRecons = srtk.ConstantImageSource()
sizeX = 256
sizeY = 256
sizeZ = 256
sizeOutput = [sizeX, sizeY, sizeZ]
sizeX = 38.016
sizeY = 38.016
sizeZ = 38.016
spacing = [sizeX, sizeY, sizeZ]
sizeX = -4863.5
sizeY = -4863.5
sizeZ = = -4863.5
origin = [sizeX, sizeY, sizeZ]
constantImageRecons.SetOrigin(origin)
constantImageRecons.SetSpacing(spacing)
constantImageRecons.SetSize(sizeOutput)
constantImageRecons.SetConstant(0.0)
imageRecons = constantImageRecons.Execute()

feldkamp = srtk.CudaFDKConeBeamReconstructionFilter()
feldkamp.SetGeometry(self.geometry)
srtkImage = feldkamp.Execute(imageRecons, srtkData)

reconstructData = srtk.GetArrayFromImage(srtkImage)

I then transform my reconstructData so to publish it. When I visualize it, I have this:

![image](https://user-images.githubusercontent.com/37636828/41675077-b39b9532-748f-11e8-8885-a9b8e74f8b23.png)
![image](https://user-images.githubusercontent.com/37636828/41675109-cd9b93a6-748f-11e8-91ab-0c845f7f6dc0.png)

I am pretty sure that my error is not in the way I visualize my image. I was wondering if anybody had encountered the same mistake as me? Or if anybody had an idea as to why it is not working for me. I should obtain something looking like this:

![image](https://user-images.githubusercontent.com/37636828/41675441-b4131200-7490-11e8-89de-62040d59de1c.png)

Thank you, 
Emmanuelle Richer

**Comment by SimonRit** [comment]
Hi Emmanuelle,
It would be a lot easier to help you if you added the code to generate the
projections data. Did you use SimpleRTK for this too?
It is clearly a geometry problem, either due to a different geometry when
generating the projection images or a problem in the conversion from numpy
array. From the images, I notice that we guess the typical axial slice of
the Shepp Logan but the cone-beam artifacts (top / bottom chinese hat) are
on the same slice which is really not expected.
My advice: do a full script which includes the simulations and if you get
that working, compare the simulated projections and the one you are using
here.
I hope this helps,
Simon

**Comment by EmmanuelleRicher** [comment]
Hi, 

Thank you so much for your quick answer!

I didn't use SimpleRTK to generate my projections. I have attached them here as a tiff stack so you can look at them. I load them as a stack of files through another software that switches them into a ndarray. 
I have 500 tif files of 256 x 256 and after the numpy conversion I have a ndarray (ndaData) of 500, 256, 256 (Z, Y, X convention). Maybe the axes convention causes problems?

I will still try your advice, to generate my projections with SimpleRTK methods and to compare the projections. I tried to reconstruct with the same code as I have now with another set of Cone Beam projections generated from a real CT machine and I still have unexpected results... 

Thank you so much, 
Emmanuelle
[SheppLoganConeBeam.zip](https://github.com/SimonRit/RTK/files/2124067/SheppLoganConeBeam.zip)

**Comment by EmmanuelleRicher** [comment]
Hi, 

Just wanted to give an update: I generated projections with RTK (with the command line options in the built applications : http://wiki.openrtk.org/index.php/RTK/Scripts/FDK) and I obtain very similar results. And when I test the reconstruction on the projections made by the command line methods, I obtain basically the same reconstruction output with lots of weird artefacts. 

But, when I input either negative values to my sad and sid distances (-20000 and -10000) or when I put my max angle negative (-360), I obtain pretty good results (see image below). I suppose there is a flaw in the way I create my geometry but I don't have any idea what it is!

![image](https://user-images.githubusercontent.com/37636828/41742173-3fa6ad74-756b-11e8-9209-b1f1f6250c6c.png)

Please tell me if you have an idea about what it is that's causing this!
Have a good day and thank you, 
Emmanuelle

**Comment by SimonRit** [comment]
Thanks for the update. That's weird indeed. Are you writing it to disk in mhd format and reading with SimpleRTK? I don't understand how this is possible to be honest. Please give the command line and the Python code to read it.

**Comment by EmmanuelleRicher** [comment]
Hi, 

So I'm getting closer to an answer. I was able to create projections with these command line options:
C:\Users\admin\Desktop\RTK-BuildExamples>rtksimulatedgeometry -n 256 -o C:\Users\admin\Desktop\RTK-BuildExamples\ExternalData\testing\Data\Baseline\XRad\geometry.xml
C:\Users\admin\Desktop\RTK-BuildExamples>rtkprojectgeometricphantom -g C:\Users\admin\Desktop\RTK-BuildExamples\ExternalData\testing\Data\Baseline\XRad\geometry.xml -o projections.tif --spacing 2 --dimension 256 --phantomfile C:\Users\admin\Desktop\RTK-BuildExamples\ExternalData\testing\Data\Input\GeometricPhantom\SheppLogan.txt

and then reconstruct them with my simpleRTK code:
_I am working with Dragonfly, I import the files in the software then with this code transform the channel containing my projections to a ndarray._ 

# Needs a channel
channelGUIDList = (
   WorkingContext.getEntitiesOfClass(self.getImplementation(), OrsSelectedObjects, Channel.getClassNameStatic()))
if len(channelGUIDList) == 0:
   return
self.channel = orsObj(channelGUIDList[0])  # Take the first one

numberOfProjections = self.channel.getZSize()

self.sdd = 1536
self.sid = 1000
anglemin = 0  # first angle
anglemax = 360  # last angle
isox = 0
isoy = 0
outangle = 0
inangle = 0
srcx = 0
srcy = 0
for noProj in range(0, numberOfProjections):
    angle = anglemin + noProj * anglemax / numberOfProjections
    self.geometry.AddProjection(self.sid, self.sdd, angle, isox, isoy, outangle, inangle, srcx, srcy)

# Convert from intensity to attenuation
ndaData = self.channel.getNDArray(0)  # working with Dragonly, that’s how I a transform my projections images in ndarray
I0 = 2 ** 16 - 1

if ndaData.min() > 0:
   intensityOffset = 0
else:
   intensityOffset = 0.01*(ndaData.max()-ndaData.min())-ndaData.min()  # offset to non negative numbers
   ndaData = np.log(float(I0)/(ndaData+intensityOffset))  # Convert intensity to line integral
   print("Attenuation range =", ndaData.min(), ndaData.max())
ndaData = ndaData.astype(np.float32)  
# must have the same dtype as the reconstructed image i.e. float32

# Convert to a SimpleRTK image
srtkData = srtk.GetImageFromArray(ndaData)
uvSize = srtkData.GetSize()
# convert to mm
spacing = [1000 * self.channel.getXSpacing(), 1000 * self.channel.getYSpacing(), 1000 * self.channel.getZSpacing()]
origin = [-0.5*spacing[0]*(uvSize[0]-1), -0.5*spacing[1]*(uvSize[1]-1), 0]  # centered
srtkData.SetSpacing(spacing)
srtkData.SetOrigin(origin)

# Create an empty output
constantImageRecons = srtk.ConstantImageSource()
sizeX = 256
sizeY = 256
sizeZ = 256
sizeOutput = [sizeX, sizeY, sizeZ]
sizeX = 1
sizeY = 1
sizeZ = 1
spacing = [sizeX, sizeY, sizeZ]
sizeX = -127.5
sizeY = -127.5
sizeZ = -127.5
origin = [sizeX, sizeY, sizeZ]
constantImageRecons.SetOrigin(origin)
constantImageRecons.SetSpacing(spacing)
constantImageRecons.SetSize(sizeOutput)
constantImageRecons.SetConstant(0.0)
imageRecons = constantImageRecons.Execute()

print("Performing reconstruction")

feldkamp = srtk.CudaFDKConeBeamReconstructionFilter()
feldkamp.SetGeometry(self.geometry)
feldkamp.SetTruncationCorrection(0.0)
feldkamp.SetHannCutFrequency(0.0)
srtkImage = feldkamp.Execute(imageRecons, srtkData)

# Convert to ndarray
reconstructData = srtk.GetArrayFromImage(srtkImage)
# Put it on a new channel
newChannel = Channel()
newChannel.resize(reconstructData.shape, dtype=reconstructData.dtype)
origin = Vector3() ; origin.setXYZ(float(self.ui.outputOriginX.text()), float(self.ui.outputOriginY.text()),
                                  float(self.ui.outputOriginZ.text()))
newChannel.setOrigin(origin)
scale = srtkImage.GetSpacing()
newChannel.setXSpacing(scale[0] / 1000)  # convert into meters
newChannel.setYSpacing(scale[1] / 1000)
newChannel.setZSpacing(scale[2] / 1000)

newChannel = createChannelFromNumpyArray(reconstructData, newChannel.getGUID())

# save to files in directory
file = self.directory + r'\file.tif'
orsimagesaver.OrsImageSaver.exportDatasetToTiffFile(newChannel.getGUID(),
                                                   fileName=file,
                                                   useLZWCompression=False,
                                                   exportMultiFrameFile=False,
                                                   showProgress=False)
if self.ui.loadChannel.isChecked():
   newChannel.setTitle('Reconstructions')
   newChannel.publish()
   print('Reconstruction complete.')
else:
   print('Reconstruction files are now in the chosen directory.')

and obtain good results. When I was trying the same reconstruction code on the projections that I posted earlier in the tif stack, I was obtaining the weird artefacts on the reconstructed images. But when I inverted the signs of sad and sid, it worked. I figured out that when I inverted the Z axis in my projections and then applied the reconstruction code, it was all working out as well. I suppose there was a difference in the way I had created my projections. I will try to understand why I need to invert an axis to make my reconstruction code work with my own projections but I will close this issue since I found out the way to obtain good reconstructed images. 

I'm sorry for not posting my code earlier but I wasn't sure if I was at liberty to do so.

Thank you for your help!
Emmanuelle

**Comment by SimonRit** [comment]
Hi,
I don't understand why you go through this path. I suggest that you do everything in Python with SimpleRTK following, e.g., the example here
http://wiki.openrtk.org/index.php/FanBeam
Then, you can try to understand what's wrong when you do your conversion via Dragon fly. My guess is that it is not using a C convention for arrays as ITK does but, maybe, a Fortran convention as numpy does. So, from ITK to numpy, the order [x,y,z] becomes [z,y,x] and it's possible that you can compensate that with some minus signs in your geometry.
Simon

**Comment by SimonRit** [comment]
Also, this is not an RTK issue but this is a user question, I would prefer to have that conversation on the mailing list rtk-users@openrtk.org dedicated to this. I'm therefore closing the issue.
