### ISSUE TITLE
Lots of "cmd.exe" exited with code 1 ERROR during building the RTK with VS2017+CUDA9.1

### ISSUE THREAD

**Issue by liuyl07** [RTKConsortium/RTK#193]
Hi guys,

I just met an issue. I tried to build the RTK under WIN10 (x64)+VS2017(with v140 toolsets because I know that there is a compatibility problem with v141 toolsets and CUDA9.1). To be exact, I only used v140 toolset for the "rtkcuda" project and remained others under v141 toolset. After rebuild the whole Visual Studio Solution, 57 errors occurred and they were all the same just shown as follows.

1>------ Rebuild All started: Project: rtkvarianprobeamgeometry, Configuration: Release x64 ------
1>Generating rtkvarianprobeamgeometry.ggo
1>CMake Error at D:/RTK1.4.0/Build/cat.cmake:6 (file):
1>  file failed to open for reading (No such file or directory):
1>
1>    D:/1
1>
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "rtkvarianprobeamgeometry.vcxproj" -- FAILED.

Can anyone help me find out what the reason is? Thanks in advance.

![rtk building error 2](https://user-images.githubusercontent.com/15646535/41805991-6b1f65dc-76e6-11e8-83b9-8502031ba397.png)
![rtk building error 3](https://user-images.githubusercontent.com/15646535/41805992-6e182120-76e6-11e8-9991-e80c7de108f4.png)
![rtk building error 4](https://user-images.githubusercontent.com/15646535/41805993-6f0c1ece-76e6-11e8-87a1-d493343d90df.png)
![rtk building error](https://user-images.githubusercontent.com/15646535/41805995-6f7a9bce-76e6-11e8-86f5-d8ee3c4c5aa7.png)

**Comment by liuyl07** [comment]
Some complements. Build RTK (v1.4.0) with CUDA9.1 under Windows 10 with Visual Studio 2017.

**Comment by liuyl07** [comment]
Just wanted to add an update related to this issue. The error occurred because the "Where is the source code" PATH which I set yesterday has some spaces. To be exact, I used "D:\1 Others\4 MY PROJECTS\ReconstructionToolKit\tags\v1.4.0", which has a space in the "1 Others" folder and another space in the "4 MY PROJECTS". After copying the RTK source code to another path (D:\RTK\Source_v1.4.0) eliminating any space, I can build and install the whole solution successfully.

**Comment by SimonRit** [comment]
Thanks for the report. Indeed, there was a problem with the spaces. It seems to be fixed with 8641ade, both for [Linux](https://my.cdash.org/viewConfigure.php?buildid=1475830) and [Windows](https://my.cdash.org/buildSummary.php?buildid=1475833).
