### ISSUE TITLE
Forward Projection Example

### ISSUE THREAD

**Issue by weianlin** [RTKConsortium/RTK#198]
Hi,

I followed the steps in 

http://wiki.openrtk.org/index.php/RTK/Scripts/ForwardProjection 

to generate projections. However, when I visualize the projections, it seems that the rotations of the source and detector are along the A-P axis. The followings are some projections.

![screenshot from 2018-07-04 15-09-01](https://user-images.githubusercontent.com/39971683/42291885-9a02b732-7f9c-11e8-8470-0c0764440ef7.png)
![screenshot from 2018-07-04 15-09-25](https://user-images.githubusercontent.com/39971683/42291893-a7d77884-7f9c-11e8-8f24-57583c878e6b.png)
![screenshot from 2018-07-04 15-09-55](https://user-images.githubusercontent.com/39971683/42291897-aac796dc-7f9c-11e8-8115-50beed33ef57.png)

My question is, shouldn't the source-detector pair rotates with respect to I-S axis? The version is

rtkforwardprojections 1.4.0, git hash 33107fb777bff65b78dd35695375a1213241610a

Thank you!

**Comment by SimonRit** [comment]
This is not an issue, please use the mailing list (rtk-users@openrtk.org) for user questions.
RTK geometry rotates around the y axis by default, see documentation [here](http://www.openrtk.org/Doxygen/DocGeo3D.html). Change your input volume if you want to change the orientation, either by flipping axes or by changing the TransformMatrix in the mhd header (which will modify the itk::Image::m_Direction, see itk documentation).
