### ISSUE TITLE
Move .txx to .hxx file extensions.

### ISSUE THREAD

**Issue by hjmjohnson** [RTKConsortium/RTK#20]
STYLE: Change for development tool compliance

PREMISE:
The  use of the .txx file extension for indicating the file
that is to hold the implementation of a template class is
only adopted by the ITK community and VNL communities (and has
slightly “infected” a few other small components of other projects).
Increasingly tools are being created to help the programmer better
understand and analyze, and provide hints to proper coding options
dynamically in the development environment (color coding, auto-completion).

The obscure .txx file requires special configuration of each development
environment tool to indicate that it is really a c++ header.  For new
developers this is often a difficult and frustrating task.  This is
confirmed by the large amount of documentation for just a few of the
common editors.  Tools that recognize and respect the .hxx extension:
uncrustify, vim, emacs, VisualStudios, clang, SlickEdit,
kwrite, etc....)  None of these tools recognize the .txx extension without
end user customizations.

CONS:
Many files will be changed, and it will not be backwards compatible for
those who accidently included the “.txx” files in their projects.  The .txx
files should not be included in external packages.

BENEFITS:
Implementation files are properly mapped to C++ language type by default
for improved development environment experience.

CONSIDERATIONS:
There is no obvious single correct solution, but in general a common theme
from other guides is that the final extension should be “.hxx” or
some suffix that ends with “.h”.  The extension should be all lower case
letters (to avoid problems on case insensitive file sysetms).

PROPOSAL:
In ITKv4 (and outside of the ThirdParty directory) change all implementation files
that currently have a “.txx” extension to have a “.hxx” extension.

An in-depth discussion was held near April 20, 2011 on the Insight-Developers
mailing list.

**Comment by SimonRit** [comment]
Thanks for the detailed issue. I am not so fond of such large changes but my collaborators agreed with you so I just applied the change. Thanks again!
