### ISSUE TITLE
Build with ITK - install package

### ISSUE THREAD

**Issue by dkuegler** [RTKConsortium/RTK#207]
If one selects "ITK_DIR" to be NOT the BUILD Dir of ITK, but the install dir, The error will be:

CMake Error at CMakeLists.txt:199 (include):
  include could not find load file:

    ITKModuleExternal

Configuring incomplete, errors occurred!
See also "G:/build-msvc15_x64/lib/rtk/CMakeFiles/CMakeOutput.log".
See also "G:/build-msvc15_x64/lib/rtk/CMakeFiles/CMakeError.log".

**Comment by dkuegler** [comment]
This error is in the configure step of cmake

**Comment by SimonRit** [comment]
RTK has moved to being an external module of ITK, maybe one cannot compile from an installed ITK. What do you think @LucasGandel?

**Comment by LucasGandel** [comment]
Exactly, even if you could provide the ITKModuleExternal.cmake script from the sources, you would hit the following error message : 

> CMake/ITKModuleExternal.cmake:11:
> message(FATAL_ERROR
> "Modules can only be built against an ITK build tree; they cannot be built against an ITK install tree.")

**Comment by SimonRit** [comment]
Thanks for the confirmation. I guess we need to clarify this in RTK's documentation. We are preparing a release for the coming days to be able to submit a file to ITK for compilation of RTK from within ITK as a remote module. For now, if you just clone RTK in ITK_SRC/Modules/Remote or in ITK_SRC/Modules/External, you will get a Module_RTK option that you can activate to compile RTK.
I'll leave this issue open until we have changed the error message for something more meaningful than what you currently have.

**Comment by dkuegler** [comment]
This should really be a new issue, but since it is easier to explain:
I moved RTK to Modules/External and activated Module_RTK.
On Windows, when compiling ITK_CudaComman as BUILD_SHARED, I get:
C2941: definition of dllimport static data member not allowed in itkCudaContextManager.cxx
This is because ITK_CudaCommon is not defined, since the target in not defined as a shared library and therefore in the itkCudaWin32Header.h, the library is defined as __declspec(dllimport) which is bogus.

Solution: in utilities/ITKCudaCommon/CMakeLists.txt:11
add_library(ITKCudaCommon ${ITK_LIBRARY_BUILD_TYPE} ${ITKCudaCommon_SRC})

If itkcudacommon should always be static, then the declspec declarations should be removed....

**Comment by dkuegler** [comment]
Also, I think the whole install infrastructure is sadly not properly set up.
I guess that is still one of the todos?

**Comment by SimonRit** [comment]
Thanks for your efforts and your patience.
On the first point, the weird part is that I successfully compile RTK nightly on Windows with shared and static libraries, see the [dashboard](http://my.cdash.org/index.php?project=RTK). I don't know why you're encountering problems I don't have. Moreover, I never see such a ${ITK_LIBRARY_BUILD_TYPE} in ITK code. Any suggestion? I'm really lost with this Windows stuff.

On the install infrastructure, I guess you have understood I'm really not skilled on this part. So yes, it's a todo but I'm not sure what is to be done. What need to be installed are includes, libraries, exe and cmake scripts. Any suggestions on how to proceed is welcome.

**Comment by agravgaard** [comment]
I think the following error is related to this issue:
I'm now getting `CMake Error: install(EXPORT "ITKTargets" ...) includes target "RTK" which requires target "lpsolve55" that is not in the export set.` when configuring ITK with RTK as a external module, during the generation step of CMake.

[Docker file, for building ITK/RTK](https://gitlab.com/agravgaard/cbctrecon/blob/AddTesting/ci/docker/gcc-7-x86_64-DCMTK363-ITKv4131-RTKmaster/Dockerfile)

**Comment by LucasGandel** [comment]
Indeed... I broke compilation within ITK while trying to fix the install step in the latest commit. I'm currently working on a fix.
In the meantime you should be able to bypass the issue if you use the "NO_INSTALL" parameter as it was done [here.](https://github.com/SimonRit/RTK/commit/5913f42b59a675ab3a34f040d3bd6949bd1f9d8f#diff-95e351a3805a1dafa85bf20b81d086e6L136)

**Comment by LucasGandel** [comment]
Building within ITK with static/shared libraries should be OK now that #209 is integrated.
You might want to give a try to latest master.

**Comment by agravgaard** [comment]
Thanks! :+1: 
It seems to work well, now it's only my own code causing my CI to fail...

**Comment by LucasGandel** [comment]
#210 adds an explicit check to prevent building against an ITK install tree.
#209 should have fixed the shared libraries issue when building within ITK.
@dkuegler Is there anything else or can we safely close this issue?

**Comment by SimonRit** [comment]
@LucasGandel I have setup a first [nightly build](https://my.cdash.org/buildSummary.php?buildid=1526518) with static / release / FFTW and it fails. It seems that a27a558 is not a good solution for this build. Are you sure it's necessary for shared libraries?

**Comment by LucasGandel** [comment]
@SimonRit Did you use a remote file? It seems that a27a558 was required when building as an external module, but not when building as a remote. It does not really makes sense to me right now, I'll investigate.

**Comment by SimonRit** [comment]
Yes, here is RTK.remote.cmake:

itk_fetch_module(RTK
    "Reconstruction Toolkit (RTK) http://www.openrtk.org/"
  GIT_REPOSITORY ${git_protocol}://github.com/SimonRit/RTK.git
  GIT_TAG master 
)

**Comment by agravgaard** [comment]
I didn't need the `RTK_BUILD_APPLICATIONS` flag, so I didn't look so deep into it, but shouldn't it be enough with an `if(NOT ITK_SOURCE_DIR)` around [find_package](https://github.com/SimonRit/RTK/blob/master/applications/CMakeLists.txt#L29) ?

**Comment by SimonRit** [comment]
That's what used to be there and @LucasGandel removed is for shared libs I believe.

**Comment by LucasGandel** [comment]
I removed it [a few month ago](https://github.com/SimonRit/RTK/commit/87aed83d0fc3d55b3b4b4f4c38427a593e60dfa4) when trying to build as a remote. I guess things have changed on the itk side and this should be added back.
@SimonRit Can you please make the change or do you want me to do it?

**Comment by SimonRit** [comment]
As far as I know, this issue is now fixed in the new release. Re-open it if required.

**Comment by Quinlly** [comment]
Hi, when I build RTK-2.0.1，there is an error " fatal error LNK1181: can't open the file “..\..\lib\Release\itkRTK-5.0.lib”". why?

**Comment by SimonRit** [comment]
I don't know. Can you open a separate issue and detail your configuration?
Thanks,
Simon

**Comment by Quinlly** [comment]
OK，I  have resolved the problem by  replacing RTK-2.0.0 with RTK-1.4.0.



suinlly@126.com
 
From: Simon Rit
Date: 2019-07-15 17:25
To: SimonRit/RTK
CC: Lizhong Qiu; Comment
Subject: Re: [SimonRit/RTK] Build with ITK - install package (#207)
I don't know. Can you open a separate issue and detail your configuration?
Thanks,
Simon
