### ISSUE TITLE
 Incorrect output with XMLReader in Release mode

### ISSUE THREAD

**Issue by kabcode** [RTKConsortium/RTK#214]
Hello,

i am using RTK together with ITK, compiled with VS2015 on Windows 7. I copied some code from the example of [rtkgeometryfiletest](https://github.com/SimonRit/RTK/blob/master/test/rtkgeometryfiletest.cxx) to read a geometry file that was written with the corresponding code from the geometryfiletest. 

In Debug mode everything is okay. Once I try the Release or RelWithDebInfo the reading process gives incorrect results. 

Code 
```c++ 
auto GeometryReader = GeometryReaderType::New();
GeometryReader->SetFilename(argv[3]);
TRY_AND_EXIT_ON_ITK_EXCEPTION(GeometryReader->GenerateOutputInformation());
auto Geometry = GeometryReader->GetOutputObject();
```

When it is compiled in Debug mode everything is fine. Once I switch to any type of Release mode it changes to something I cannot explain. See attached image for the variable Geometry first in Debug mode then Release mode. Derived from the same code and geometry file.
![geometrydebug](https://user-images.githubusercontent.com/20195456/46317058-3d79da00-c5d2-11e8-8867-10aaa3010277.png)

![geometry](https://user-images.githubusercontent.com/20195456/46316966-f55ab780-c5d1-11e8-9038-1474de0d1b7a.png)

it becomes more strange when I print the projection matrices using 
```c++
Geometry->Print(std::cout);
```
the printed information is the correct projection matrix in both cases. 

unfortunately I cannot provide a solution. Is this behavior of the XMLReader known? Does a workaround exist or is it another error?
Maybe someone can reproduce it. 

Sincerly,
Gordian

**Comment by SimonRit** [comment]
Hi Gordian,
No, I am not aware of this behavior and it's certainly unknown. Can you provide the code that you're using and the ITK version?
Or, even better, maybe you can try to investigate where the problem is with breakpoints?
Thanks,
Simon

**Comment by kabcode** [comment]
I investigated the problem an it turns out that in the end the compiled ITK version i was using was not the one I thought. After an update everything is okay. Thank you for your hint. You can close this issue. Sorry for bothering you.

Best,
Gordian

**Comment by SimonRit** [comment]
No pb, thanks for the update.
