### ISSUE TITLE
Building python wheel for RTK failing

### ISSUE THREAD

**Issue by rsnk96** [RTKConsortium/RTK#221]
The documentation at http://wiki.openrtk.org/index.php/ is outdated and says the SimpleRTK module is needed. However, the SimpleRTK module is no longer needed and there is a setup.py file directly in the RTK directory itself. I'm unable to install using it though.

It would be nice if the documentation could be updated on how to use the updated Python module

**Comment by SimonRit** [comment]
Yes, the wrapping is being updated. We haven't updated the doc yet but we will before RTK's release. Basically, you can look at ITK's documentation for using those packages. If you want pre-compiled packages, I have a few [here](http://www.creatis.insa-lyon.fr/~srit/rtk_python_packages) which require  the ITK packages [v5.0b01](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/releases/tag/v5.0b01).

**Comment by SimonRit** [comment]
With the recent release of RTK v2 and associated python packages, SimpleRTK is no longer maintained and I suggest to use the new packages.
