### ISSUE TITLE
CMake files reference de-commissioned urls at midas3.kitware.com

### ISSUE THREAD

**Issue by simonkrogh** [RTKConsortium/RTK#230]
The following files contain links to midas3.kitware.com. My guess is that these should be updated to data.kitware.com-links

cmake/RTKExternalData.cmake
utilities/SimpleRTK/SuperBuild/External_Swig.cmake
utilities/SimpleRTK/SuperBuild/External_virtualenv.cmake
utilities/SimpleRTK/CMake/srtkExternalData.cmake

**Comment by SimonRit** [comment]
With the recent release of RTK v2 and associated python packages, SimpleRTK is no longer maintained and I suggest to use the new packages. RTKExternalData has been updated in the release.
