### ISSUE TITLE
rtkfdk and rtkconjugategradient broken?

### ISSUE THREAD

**Issue by dericdesta** [RTKConsortium/RTK#237]
Hi Simon,
first of all thank you (and your collaborators) very much for this great framework!

Unfortunately, I experience some odd bugs when trying to reproduce FDK (and CG) reconstructions of the SPARE data set.

## Environment & setup:
- Ubuntu 18.04.1 LTS (64-bit)
- Intel® Xeon(R) CPU E5-2620 v4 @ 2.10GHz × 32
- 64 GB RAM
- 2 × GeForce GTX 1080 Ti
- Cuda compilation tools, release 9.0, V9.0.176

Two compiled versions of RTK:
- last commit 075d0a85924fccaf91f161c4e9bc2791bbf189a9 (hereinafter referred to as 'latest')
- release v1.4.0

For both versions all tests passed.

## Possible bugs
Please find respective files for reproducing the issues [here](https://icns-nas1.uke.uni-hamburg.de/owncloud/index.php/s/7gzIdVDafaLLyFZ).

The following reconstructions refer to `Patient CV_P1_T_01` of the clinical Varian data set of SPARE.
### 1) Broken FDK?
In `/bin_08_fdk` you can find
- the reference SPARE reconstruction of bin 8 (`reference_FDK4D_08.mha`) provided by the challenge
- my reconstruction of bin 8 using `rtkfdk` with the following parameters
```python
{'path': '...',
'regexp': '^projections_binned',
'geometry': '.../geometry.xml',
'hardware': 'cuda',
'dimension': (450, 220, 450),
'spacing': (1.0, 1.0, 1.0),
'pad': '1.0',
'hann': '0.7',
'hannY': '0.7',
'output': '.../bin_08_fdk.mha'}
```
- used (subselected) `geometry.xml` and down-scaled projection data (2x2 subsampled), 38 projections for bin 8.

As you can see from the following images it seems like some projections are ignored.
The average reconstruction is fine though! This issue does not occur with every bin; e.g., bin 1-6 and 9 are fine and de-facto identical to SPARE reference reconstruction `FDK4D_0x.mha`. Only bin 7, 8 and 10 have this strange artifact.
It looks like this issue is more likely if less projections are available. This bug occurs both with latest version and v1.4.0 (independent of whether I use CUDA or CPU). I also experienced this bug in the past using in-house Varian half-fan beam data.
![fdk_ref](https://user-images.githubusercontent.com/7849983/52130780-6622e680-263b-11e9-8aa7-129bc5a5b32b.png)

![fdk_issue](https://user-images.githubusercontent.com/7849983/52130785-691dd700-263b-11e9-952e-24aa9c05441e.png)

If I replace `rtkfdk` (latest version) with `rtkconjugategradient` (v1.4.0) using
```python
{'path': '...',
'regexp': '^projections_binned',
'geometry': '.../geometry.xml',
'fp': 'CudaRayCast',
'bp': 'CudaVoxelBased',
'dimension': (450, 220, 450),
'spacing': (1.0, 1.0, 1.0),
'niterations': 10,
'output': '.../bin_07_cg.mha'}
```
everything is looking good (see `/bin_08_cg/bin_08_cg_v140.mha`). Thus, I would assume that the geometry and projections are correct.

![cg_v140](https://user-images.githubusercontent.com/7849983/52130800-70dd7b80-263b-11e9-89a1-f84621b2a00a.png)

But here, another issue comes up...

### 2) CG: latest version vs. v1.4.0
If I use the latest version, `rtkconjugategradient` seems to have another issue regarding detector displacement (same recon params as in 1):

![cg_latest](https://user-images.githubusercontent.com/7849983/52130804-75099900-263b-11e9-9a85-7c83ff17607a.png)

------
Many thanks in advance for any help!
Best regards from Hamburg and @renewerner :blush:

**Comment by SimonRit** [comment]
Dear @dericdesta and @renewerner,
Thanks a lot for your reports, very helpful.
1/ The problem is that you have so huge gaps in your angles that RTK detects a short scan. There was a hard-coded 20° limit. This is now configurable and you can disable short scan weighting with "--short 360" on the rtkfdk command line.
2/ Yes, in the process of making the conjugate gradient compatible, @cyrilmory disabled the displaced detector weighting which I had wrongly put back in. The same behavior as RTK 1.4 should now be observed.
These changes (see above) just made it to a new RTK release which I intend to make today. Thanks again,
Simon

**Comment by dericdesta** [comment]
Dear Simon,
thank you very much for fixing these bugs so fast!

Best regards,
Frederic
