### ISSUE TITLE
Output for test in Debug/Release mode of ITKv5.0rc01 with RTK

### ISSUE THREAD

**Issue by kabcode** [RTKConsortium/RTK#238]
Hello Simon,

I would like to give you some building and testing feedback on the ITK together with the RTK.
My system is  Windows 7 64bit, Cmake 3.13, Visual Studio 2015. TBB and GDCM were available in the latest stable version. CUDA 9.0 and VTK 8.0 are installed. 
Anything else you need to know? Do you need other files or outputs?

Here are the copied output of the test results from the Debug and RelWithDebInfo testing and the CMakeCache.
[CMakeCache.txt](https://github.com/SimonRit/RTK/files/2871089/CMakeCache.txt)
[ITK5withRTK_RelWithDebInfo.txt](https://github.com/SimonRit/RTK/files/2871082/ITK5withRTK_RelWithDebInfo.txt)
[ITK5withRTK_Debug.txt](https://github.com/SimonRit/RTK/files/2871084/ITK5withRTK_Debug.txt)

BTW thank you for your great work.

**Comment by SimonRit** [comment]
Can you check #244 and tell me if that fixes your RTK issues?

**Comment by SimonRit** [comment]
Can we close this issue or are you still having problems? I don't encounter problems on both linux and windows since the fix. It's just slower with is than without

**Comment by kabcode** [comment]
This issue can be closed. No issues in this case anymore. Thx.
