### ISSUE TITLE
rtkConfiguration.h is not installed when RTK 2.0 is build as a submodule of ITK 5.0 RC 1

### ISSUE THREAD

**Issue by Siron777** [RTKConsortium/RTK#240]
I have built ITK 5.0 RC 1 on visual studio 2017 15.9.7 with RTK 2.0 as a submodule. When I build a project against the installation of this build, it does not find the header rtkConfiguration.h which is included in rtkConstantImageSource.h. The headers are present in the build folder of ITK, but not in the installation folder.

Version
5.0rc1, with RTK 2.0

Environment

Windows 10
Visual studio 2017 15.9.7
Compilation in 64 bits
Ninja
cmake command: cmake "D:/dev/library/source/ITK-5.0rc01" -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH=D:/dev/library/x86-64_msvc2017/itk/5.0_rc1 -DModule_RTK=ON -DRTK_BUILD_APPLICATIONS=OFF -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_DEBUG_POSTFIX=d -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DCUDA_TOOLKIT_ROOT_DIR=D:/dev/conan_c/Cuda/10.0/AI/extern/package/479e5c321685f6e20cbbf93c38ae334c54ade580

**Comment by SimonRit** [comment]
@LucasGandel The whole installation architecture of RTK is really messy and I have the feeling it is not done at it should. Installation variables are defined in the main CMakeLists.txt ([here](https://github.com/SimonRit/RTK/blob/master/CMakeLists.txt#L46)) but redefined in the macro itk_module_impl. As pointed out in this issue, rtkConfiguration.h is not installed and I'm not sure the rest is installed properly either. Do you know how to clean this?

**Comment by LucasGandel** [comment]
@SimonRit You are right, I'll add this to the current to-do list.
Adding the missing rtkConfiguration.h file should be fairly easy. Cleaning the overall process is trickier as we want to support both standalone installation and installation within ITK.

**Comment by SimonRit** [comment]
Thanks. My first attempt to add the rtkConfiguration.h did not work out because RTK_INSTALL_INCLUDE_DIR is wrongly set [here](https://github.com/SimonRit/RTK/blob/master/CMakeLists.txt#L56) I believe (should be [ITK_INSTALL_INCLUDE_DIR](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKModuleMacros.cmake#L138) according to the module macro and this is different).

**Comment by LucasGandel** [comment]
Right but then I think RTK would always be installed in ITK (which I think is undesired when building RTK against an ITK build tree).
Maybe we should unset those variable when building within ITK.
I'll discuss with CMake experts to see what they think is best.

**Comment by SimonRit** [comment]
I maybe wrong but I don't think we can avoid that RTK gets necessarily installed with ITK. Maybe that's a question for ITK's discourse (can an external module be installed in another directory than ITK's install?).

**Comment by SimonRit** [comment]
Fixed by #246 it seems
