### ISSUE TITLE
RTK_VERSION_STRING of rtkConfiguration.h is an empty string

### ISSUE THREAD

**Issue by Siron777** [RTKConsortium/RTK#247]
I have built ITK 5.0 RC 2 on visual studio 2017 15.9.7 with RTK 2.0 as a submodule. The macro RTK_VERSION_STRING in the header rtkConfiguration.h is configured with an empty string. The other version number macros are fine.

Version
ITK 5.0rc2, with RTK 2.0

Environment

Windows 10
Visual studio 2017 15.9.7
Compilation in 64 bits
Ninja
cmake command: cmake "D:/dev/library/source/ITK-5.0rc02" -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH=D:/dev/library/x86-64_msvc2017/itk/5.0_rc2 -DModule_RTK=ON -DRTK_BUILD_APPLICATIONS=OFF -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_DEBUG_POSTFIX=d -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DCUDA_TOOLKIT_ROOT_DIR=D:/dev/conan_c/Cuda/10.0/AI/extern/package/479e5c321685f6e20cbbf93c38ae334c54ade580

**Comment by SimonRit** [comment]
Commit f13a281 should fix this. Thanks for the report!
