### ISSUE TITLE
Target ITKCudaCommon, RTK hardcode the absolute path to the CUDA lib

### ISSUE THREAD

**Issue by Siron777** [RTKConsortium/RTK#248]
I have built ITK 5.0 RC 2 on visual studio 2017 15.9.7 with RTK 2.0 as a submodule. In the ITKTargets.cmake, the target ITKCudaCommon and RTK hard code the absolute path to the CUDA lib:

```
set_target_properties(ITKCudaCommon PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-5.0"
  INTERFACE_LINK_LIBRARIES "ITKCommon;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cuda.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudart_static.lib"
)
```

```
set_target_properties(RTK PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override;cxx_constexpr;cxx_range_for;cxx_rvalue_references;cxx_static_assert;cxx_strong_enums;cxx_lambdas;cxx_noexcept;cxx_alias_templates"
  INTERFACE_LINK_LIBRARIES "ITKCommon;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCudaCommon;ITKCommon;ITKStatistics;ITKTransform;ITKIOCSV;ITKIOGDCM;ITKIOMeta;ITKIOImageBase;ITKIOTIFF;ITKIOXML;ITKStatistics;ITKOptimizers;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh;ITKOptimizers;ITKCommon;ITKStatistics;ITKTransform;lpsolve55;ITKCudaCommon;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudart_static.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cuda.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cufft.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cublas.lib"
)
```

This is problematic when someone has a different installation path for cuda.

Version
ITK 5.0rc2, with RTK 2.0

Environment

Windows 10
Visual studio 2017 15.9.7
Compilation in 64 bits
Ninja
cmake command: cmake "D:/dev/library/source/ITK-5.0rc02" -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH=D:/dev/library/x86-64_msvc2017/itk/5.0_rc2 -DModule_RTK=ON -DRTK_BUILD_APPLICATIONS=OFF -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCMAKE_DEBUG_POSTFIX=d -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DCUDA_TOOLKIT_ROOT_DIR=D:/dev/conan_c/Cuda/10.0/AI/extern/package/479e5c321685f6e20cbbf93c38ae334c54ade580

**Comment by SimonRit** [comment]
Thanks for the report. No clue how to solve this, I may be wrong but I think it's a cmake issue...

**Comment by finetjul** [comment]
It seems that this issue is fixed.

**Comment by SimonRit** [comment]
Thanks, let's close it and reopen it if necessary.
