### ISSUE TITLE
'ITK_MAX_THREADS': undeclared identifier

### ISSUE THREAD

**Issue by Neumann-A** [RTKConsortium/RTK#249]
g:\test\vcpkg\buildtrees\itk\itk\modules\remote\rtk\include\rtkJosephForwardAttenuatedProjectionImageFilter.h(86): error C2065: 'ITK_MAX_THREADS': undeclared identifier (+ a few other occourences)

According to a quick search within the sources of itk `ITK_MAX_THREADS `has been moved into the itk namespace `itk::ITK_MAX_THREADS`

**Comment by SimonRit** [comment]
Thanks for the report, this occurred with ITK_FUTURE_LEGACY_REMOVE ON. Fixed by db27af0.
