### ISSUE TITLE
Update to C++17 - Deprecated functions

### ISSUE THREAD

**Issue by kabcode** [RTKConsortium/RTK#251]
Hello Simon,

i am building RTK as remote module to ITK 5 using C++17 with VS 2017. Almost everything works fine. The errors I encountered are listed below with a possible solution. I guess you might prefer another solution but those worked in my case.

* ITK_MAX_THREADS should be moved to the itk namespace: itk::ITK_MAX_THREADS 
ITK migration guide: 

> The variables ITK_MAX_THREADS and ITK_DEFAULT_THREAD_ID are now in the itk:: namespace. Backwards compatibility is currently supported by exposing these to the global namespace with
> 
>   using itk::ITK_MAX_THREADS;
>   using itk::ITK_DEFAULT_THREAD_ID;

* std::random_shuffle is deprecated since C++11 and now its gone. The child classes of rtkIterativeConeBeamReconsturctionMethods are using this function. The suggestions is to replace it with std::shuffle that needs a random generator. I am using the std:.default_random_engine.
Does the random output need some special properties? There are some more random generators.

* std::binary_function was removed aswell. This can be replaced with simple code from [SO](https://stackoverflow.com/a/56001387/3921660) or custom functions.

* This might not be a problem right now but the compiler warns about the removal of the math_function.h in upcomming CUDA version. The warning reads: 

> warning: "#warning "math_functions.h is an internal header file and must not be used directly. This file will be removed in a future CUDA release. Please use cuda_runtime_api.h or cuda_runtime.h instead."

Hope this will be helpful to you to keep the cool project uptodate!

**Comment by SimonRit** [comment]
Hi,
Thanks.

> ITK_MAX_THREADS should be moved to the itk namespace: itk::ITK_MAX_THREADS
ITK migration guide:

This has already been addressed by db27af04. Is it not working for you?

> std::random_shuffle is deprecated since C++11 and now its gone. The child classes of rtkIterativeConeBeamReconsturctionMethods are using this function. The suggestions is to replace it with std::shuffle that needs a random generator. I am using the std:.default_random_engine.
Does the random output need some special properties? There are some more random generators.

No, your suggestions look good.

> std::binary_function was removed aswell. This can be replaced with simple code from SO or custom functions.

We are not using it, are we?

> This might not be a problem right now but the compiler warns about the removal of the math_function.h in upcomming CUDA version.
We would need to test if its inclusion is still required 1539f8b.

Would you consider submitting a patch for all this?

**Comment by kabcode** [comment]
Hi,

i am using the RTK as an remote module for the ITK. I modified the module that CMake cloned during the connfiguration of the ITk project. 
How can I create a patch from the remote module or do I have to make a fork from the RTK and add the changes there before making a PR? (In the second case I would have two independent RTK clones).

**Comment by SimonRit** [comment]
Hi,
If I understand correctly, RTK has been downloaded during ITK's compilation, you modified it and you want to create a PR with these modifications. The best solution I believe is to fork RTK from github, add a remote in the RTK clone, in your case
``git remote add myremotename git@github.com:kabcode/RTK.git``
where myremotename is the name you want to give to your personal remote. Then, create a branch (let's call it mybranch) and commit your changes, push it to your own remote
``git push -u myremotename mybranch``
You can then create a PR from github.
Note that during compilation, ITK will switch back to the branch given in RTK.remote.cmake. So you can modify it to point to your own remote and the branch of your choice.
I hope this answers your question,
Simon

**Comment by kabcode** [comment]
Thank you for the guide. Following the steps worked quite well. Only minor issues with the ssh keys. Its going to be my first pull request. :-)
If you have hints or critique I am happy to get feedback to improve my contribution to open-source projects like RTK.
