### ISSUE TITLE
Add static constexpr member GPUCapable for more convenience

### ISSUE THREAD

**Issue by kabcode** [RTKConsortium/RTK#257]
Hello,

i would like to suggest to add an `static constexpr GPUCapable = true` to the CudaImage.
One advantage would be to select the data generation function (`GPUGenerateData()` or `GenerateData()`) at compile time and enable the use of `itk::Image` with the cuda-based filters from the RTK (if there is an ITK parent filter). This may allow for providing `itk::Image` to an RTK filter and cast it internally to an `itk::CudaImage`.
At the moment the the member m_GPUEnabled is set to true if RTK_USE_CUDA=ON. This global flag will not be dismissed but the member variable makes things more convenient.

A simple example of the idea is shown here: [Test with static constexpression member](https://github.com/kabcode/TKTest/tree/master/StaticConstVar/src)

The developer from the ITK need to add the same static variable GPUCapable to the `itk::DataObject`.  Since this variable is not checked in the whole ITK, it should not break anything. 

Do you have other plans for the ITkCudaCommon?

**Comment by SimonRit** [comment]
Hi,
Thanks for the suggestion. The link with the test does not seem to work. ITKCudaCommon is (originally) based on the GPUCommon module of ITK so I guess you could open this discussion to ITK (if you do so, please notify this thread). With this other module in mind, GPUCapable and CUDACapable are two different things.
I don't really see the point of what you're suggesting to be honest, a CudaImage is GPUCapable by definition... Are you not mixing data and process objects ? It seems wrong to add a GPUCapable flag to DataObject but things will most likely get clearer with your example, send it along please!
Thanks,
Simon

**Comment by kabcode** [comment]
Hi,

i had the example code set to private. [Now it is public and can be accessed](https://github.com/kabcode/TKTest/tree/master/StaticConstVar/src). It is rather a simple example of the idea. Mainly the Run() method represents my initial thoughts. 
The choice of the data generation is not decided by the RTK_USE_CUDA external flag but rather by the DataObject itself. In this way one could combine all types of images with all process objects. In RTK this would replace the `m_GPUEnabled` member variable within `CudaImageToImageFilter`.

My idea may have originated from the idea to unify the types of ProcessObject. Instead of having a derivded GPU-compatible class for every CPU class the execution path can be integrated into a single class. If no GPU option is available or reasonable the data generation is shifted back to the CPU option.

I admit that I didn't thought everything through therefore I appreciate your critical response.
Thanks,
Gordian

**Comment by SimonRit** [comment]
Hi,
Thanks for sharing the example code. It seems to me that this is a major change with very limited benefit. At this stage, I would prefer to leave ITKCudaCommon aligned with GPUCommon in ITK. So if you can convince the ITK community to modify GPUCommon in this way, I would agree with the same changes in ITKCudaCommon. Maybe you can start a conversation on discourse to see what they think?
Simon
