### ISSUE TITLE
rtkspectralonestep.cxx with nMaterials = 2

### ISSUE THREAD

**Issue by paRodesch** [RTKConsortium/RTK#258]
rtkspectralonestep uses rtk::MechlemOneStepSpectralReconstructionFilter with a fixed nMaterials set to 3. I have modified the code to use this filter for nMaterials  = 2. Code is here : 

[https://github.com/SimonRit/RTK/compare/master...paRodesch:one_step_two_materials](url)

But the change of nMaterials from 2 to 3 is hard coded in rtkspectralonestep.cxx. I want to be able to declare rtk::MechlemOneStepSpectralReconstructionFilter with either nMaterials = 2 or 3 according to the first dimension of args_info.attenuations_arg given as input of the command.

**Comment by SimonRit** [comment]
Adressed by d48e996
