### ISSUE TITLE
ITK_LEGACY_REMOVE=ON breaks build

### ISSUE THREAD

**Issue by kabcode** [RTKConsortium/RTK#263]
Hello,

If you use the ITK_LEGACY_REMOVE=ON configuration this commit will break the build of the RTK:
[ENH: Mark deprecated GDCM API as ITK legacy remove](https://github.com/InsightSoftwareConsortium/ITK/commit/71c90c83de8631e655144ad9eb6a462bcf059f56#diff-b234919c5e3253231f6e965cf2b61634)

This leads to following errors:
```
rtkDCMImagXImageIOFactory.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl itk::GDCMImageIO::GetLoadSequences(void)const " (?GetLoadSequences@GDCMImageIO@itk@@UEBA_NXZ)
rtkDCMImagXImageIOFactory.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl itk::GDCMImageIO::LoadSequencesOff(void)" (?LoadSequencesOff@GDCMImageIO@itk@@UEAAXXZ)
rtkDCMImagXImageIOFactory.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl itk::GDCMImageIO::LoadSequencesOn(void)" (?LoadSequencesOn@GDCMImageIO@itk@@UEAAXXZ)
rtkDCMImagXImageIOFactory.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl itk::GDCMImageIO::SetLoadSequences(bool)" (?SetLoadSequences@GDCMImageIO@itk@@UEAAX_N@Z)
rtkDCMImagXImageIOFactory.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl itk::GDCMImageIO::SetMaxSizeLoadEntry(long)" (?SetMaxSizeLoadEntry@GDCMImageIO@itk@@UEAAXJ@Z)
...\ITK\bin\RelWithDebInfo\itkRTK-5.1.dll : fatal error LNK1120: 5 unresolved externals
```

I did not findthe connection between the rtkDCMImagXImageIOFactory and the itkGDCMImageIO since the mentioned methods are not used.
I was able to reproduce this behavior on different systems.

Used system: Windows, ITK-master, RTK-master, VS17 with C++17

**Comment by SimonRit** [comment]
Thanks for opening an issue, it's actually been caught by our [nightly dashboard](https://my.cdash.org/index.php?project=RTK&date=2019-10-29) but it's now [solved](https://my.cdash.org/index.php?project=RTK) thanks to InsightSoftwareConsortium/ITK#1368.
