### ISSUE TITLE
rtkfourdrooster TV and TNV give same result

### ISSUE THREAD

**Issue by LukasSchroder** [RTKConsortium/RTK#264]
Hello,

I use rtkfourdrooster to reconstruct dual-energy (two image frames) CBCT images. The problem is that the reconstructed image when using total nuclear variation (gamma_tnv) is (almost) the same as when using total variation in space (gamma_space). All the other parameters are the same. I would expect some difference due to use of different threshold filters (SingularValue vs. Magnitude). The rest of the pipeline seems to be the same. 

Regards,
Lukas

**Comment by SimonRit** [comment]
Hi Lukas,
Following your recent paper (https://dx.doi.org/10.1088/2057-1976/ac4e2e), can you confirm that TNV does not give the same result and that this issue can be closed?
Thanks, Simon

**Comment by LukasSchroder** [comment]
Hello Simon, 
Yes, that is correct. The issue can be closed. 
Thanks.
