### ISSUE TITLE
Python crashes when geometry is not set in some filters

### ISSUE THREAD

**Issue by SimonRit** [RTKConsortium/RTK#270]
All filters using the geometry object should test that it's adequately set and issue an exception if not.

**Comment by acoussat** [comment]
Is there a list of filters that should be fixed somewhere? I would like to fix that but I don't feel like testing every single filter...

**Comment by SimonRit** [comment]
I would use something like `grep Geometry include/*.h | grep itkSet | sed "s/:.*$//g"`. I recently discovered that this sort of things should be implemented in `VerifyPreconditions` in ITK filters. Check for examples in the ITK code...

**Comment by SimonRit** [comment]
As far as I know, this issue is solved thanks to @acoussat. I'm closing it
