### ISSUE TITLE
ITKCudaCommon tests are not built

### ISSUE THREAD

**Issue by kabcode** [RTKConsortium/RTK#287]
Hi,

i notices that the ITKCudaCommon test are built only if the CMake variable "ITK_USE_CUDA" is set to true. After some investigation (hopefully with enough depth) I came to the conclusion that this variable is not set. Neither in ITK nor in RTK. In ITK the variable "ITK_USE_GPU" and for RTK the variable "RTK_USE_CUDA" is available.

What was the original intent of "ITK_USE_CUDA"?
Do I miss something or could it be changed to "RTK_USE_CUDA"?

**Comment by SimonRit** [comment]
Hi,
Thanks for spotting this. I guess the original intent was to have an option mirroring ITK_USE_GPU. You're right that it could be changed to RTK_USE_CUDA but this code is already in use only if RTK_USE_CUDA is ON and this is supposed to be a module independent of RTK. I'll simply delete the if.
Simon

**Comment by kabcode** [comment]
After applying your suggested change other bugs occured.
The first one is fairly simple to fix - just replace in `itkCudaReduction.hxx` follwoing line
` if (m_CudaDataManager == (CudaDataPointer) NULL)`
with
` if (m_CudaDataManager == (CudaDataPointer) nullptr)`.

Then I got two errors LNK2019 (unresolved external) with
`LNK2019	unresolved external symbol "__declspec(dllimport) public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl itk::CudaImageOpsKernel::GetCudaPTXSource(void)" (__imp_?GetCudaPTXSource@CudaImageOpsKernel@itk@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl itk::CudaImageOps::GetCudaPTXSource(void)" (?GetCudaPTXSource@CudaImageOps@itk@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)	ITKCudaCommonTestDriver	"...\Remote\RTK\utilities\ITKCudaCommon\test\itkCudaImageTest.ob`j"	

Those errors are not relevant to me and I do not any experience regarding PTX source code.

**Comment by SimonRit** [comment]
Thanks for the report. I don't seem to have these problems on our Windows box (see [dashboard](https://my.cdash.org/index.php?project=RTK)). I suspect a problem with decorations for Windows static libraries. Can you try the following please?
- replace all occurences of ITK_EXPORT by ITKCudaCommon_EXPORT in ITKCudaCommon (that's not the issue I believe but it's worth cleaning the code)
- replace [this line](https://github.com/SimonRit/RTK/blob/master/utilities/ITKCudaCommon/CMake/itkCUDA.cmake#L67) by
`std::string ITKCudaCommon_EXPORT ${GPUFILTER_KERNELNAME}::GetCudaPTXSource()`
If that doesn't help, maybe @LucasGandel can help... just give us more details on your compiler and whether RTK is built at the same time as ITK or separately. Thanks in advance!

**Comment by kabcode** [comment]
My build system is Windows 7 64bit, Visual Studio 2017 (compiler x64), CMake, SHARED_LIB=ON, Cuda v10.1, CUDA=ON, ITK_REMOVE_LEGACY=ON. RTK is build as internal remote module for ITK. For the current test I used the RTK-master branch (forked but even with upstream/RTK-master).

I replaced all ITK_EXPORT in ITKCudaCommon by ITKCudaCommon_EXPORT that is defined in `itkCudaWin32Header.h`.  Then I built all ITK and ITKCudaCommon projects in Debug. ITKCudaCommon produced a dll file but RTK was not build due to the error:
`C2491	'itk::CudaImageDataManager<ImageType>::PrintSelf': definition of dllimport function not allowed	RTK	c:\tk\src\itk-fork\modules\remote\rtk\utilities\itkcudacommon\include\itkCudaImageDataManager.hxx	152	
`
This error showed up for all uses of ITKCudaCommon in RTK (~900 times). I might reverse the last change and see if the errors persist.

EDIT: After I changed back to ITK_EXPORT everything is fine. itkRTK.dll was built.

**Comment by kabcode** [comment]
I tried the second suggestion without success. Even with `ITK_EXPORT `I had no success. In the same file a variable named `_BUILD_CUDA_KERNEL `is used. As far as I have investigated it is nowhere set in ITKCudaCommon. It is not a CMake option (I am using CMake-gui). It is used in `itkCuda.cmake`.
It can create kernels that are used in the tests but `generate_cuda_ptx_wrappers` is nowhere called to create kernel files.
**What is the purpose of keeping  and not using itkCuda.cmake?**

**Comment by agravgaard** [comment]
I am having the same problem, and looked into it:

It looks like the two files (`CudaImageOps.cu` & `CudaReduction.cu`, created at commit 1d06ae7 ) which would be needed to generate the PTX files have been deleted at commit:  e0d6f1f7bff8befb72df178ccc101e5246dbef1a

The only call to `generate_cuda_ptx_wrappers` was deleted at the same commit, so that means that **these tests should not have been able to compile since then (2013)** (unless one has been re-configuring in the same build directory since then perhaps).

Since the files doesn't exist anymore, it shouldn't be necessary to test them, and the associated test should probably be deleted as well as the unused CMake script.

**Comment by SimonRit** [comment]
Thanks Andreas for looking into it. I admit I'm lost: I don't understand why you guys are compiling (or trying to compile) this part of the code and none of the dashboard compilations does it. Any clue? @LucasGandel?
What you're saying makes a lot of sense. I would be in favor of trying to bring these tests back in place, I don't understand why they've been deleted (my commit message for e0d6f1f is a bit obscure). They test things that we don't currently use in RTK and it would be useful to keep them. I'll have a look whether this is doable...

**Comment by agravgaard** [comment]
I think the CI doesn't catch it because it's necessary to have both CUDA and RTK as an ITK module to trigger the tests, though I've not tested other configurations (than the one below) myself

- AppVeyor & CircleCI: No CUDA.
- TravisCI: Doesn't build as ITK module at the same time as CUDA.
- CDash: Missing `RTK_USE_CUDA` or `Module_ITKCudaCommon` for the "InITK" builds ?*

(*I'm not experienced in CDash, so I may have missed something)

My configuration command:
```
export CC=cl
export CXX=cl

cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_FLAGS_RELEASE:STRING="-MT -O2 -Ob2 -DNDEBUG" \
        -DCMAKE_C_FLAGS_RELEASE:STRING="-MT -O2 -Ob2 -DNDEBUG" \
	-DCMAKE_CXX_STANDARD=17 \
	-DBUILD_SHARED_LIBS=OFF \
	-DITK_BUILD_DEFAULT_MODULES=OFF \
	-DITK_USE_KWSTYLE=OFF \
	-DModule_ITKReview=ON \
	-DModule_ITKDCMTK=ON \
	-DModule_ITKDeprecated=ON \
	-DModule_RTK=ON \
	-DModule_ITKCudaCommon=ON \
	-DRTK_USE_CUDA=ON \
	-DREMOTE_GIT_TAG_RTK=master \
	-DITK_USE_FFTWF=ON \
	-DITK_USE_FFTWD=ON \
	-DITK_USE_MKL=ON \
	-DITK_USE_CUFFTW=OFF \
	-DITK_USE_SYSTEM_DCMTK=ON \
	-DDCMTK_DIR=/c/Users/andreas/Projects/DCMTK/build-rel/
```
_(Reason for the bash syntax: I run it as a bash script in "Git Bash" on Windows 10, where I've practically copied the `%Path%` from a MSVC 2019 x64 CMD prompt to my `$PATH` , I then run `ninja` from the MSVC CMD prompt )_

I think it will be necessary to add the `.cu` files again and the `generate_cuda_ptx_wrappers` call to the [CMakeLists.txt](https://github.com/SimonRit/RTK/blob/master/utilities/ITKCudaCommon/test/CMakeLists.txt), if you want to make the tests compile.

**Comment by SimonRit** [comment]
Ok, I think the `-DModule_ITKCudaCommon=ON` explains it. It's not mandatory but it should be set automatically, see [here](https://github.com/SimonRit/RTK/blob/master/itk-module.cmake#L32-L36) but maybe this does not work as expected. I'll give it a try and keep you posted.
Thanks for the reminder, I was aware of these necessary changes. You have prepared the ground by finding the wrong commits, that will help.

**Comment by SimonRit** [comment]
I managed to reproduce the problem. Let me know if you can confirm that fc70a70 fixes the problem. I'll also run tests on the dashboard (which does the cuda tests on Windows and Linux). Thanks guys!

**Comment by kabcode** [comment]
@SimonRit 45af4dd supersedes fc70a70. We dont need to run the ITKCudaCommon tests anymore as you requested in your last comment?

**Comment by agravgaard** [comment]
LGTM 👍
With the `ITKCudaCommon_tests` (at commit 45af4dd) branch everything compiled and all tests, except `ITKCudaCommonInDoxygenGroup`, passed for me

**Comment by SimonRit** [comment]
These CudaCommon tests were not running since 2013 as pointed out by @agravgaard. I tried to restore them but I think this code is not compatible with having multiple CUDA architectures which I want to keep. For the time being, I removed them and I'll open an issue.
