### ISSUE TITLE
Inconsistency in corner calculations for displaced detector

### ISSUE THREAD

**Issue by SimonRit** [RTKConsortium/RTK#290]
Issue raised by Gabriele Belotti on the mailing list: "On a smaller note, there is some inconsistency in the inferior/superior image corner calculation between positive and negative isocenter projection displacements of the same entity (say + or - 140), which in turn affect “theta” calculation."

**Comment by GabrieleBelotti** [comment]
I've found the origin of this inconsistency:
https://github.com/SimonRit/RTK/blob/45af4dd4341ba33ed216d54c6a7aeaff5d0d1fd5/include/rtkDisplacedDetectorImageFilter.hxx#L118-L120

Subtracting 1 to the size creates a different starting guess for positive and negative displacements.
From my understanding this is a small bug in the calculation of the corners of the image and the -1 should be removed from both lines (either negative and positive spacing).

Side note: I will include this quick fix in https://github.com/SimonRit/RTK/pull/291 as this solves my reconstruction problems (the artifacts is now absent)

**Comment by SimonRit** [comment]
Closing because it could not be reproduced, see conversion in #291.
