### ISSUE TITLE
Module_RTK option is missing during ITK compilation

### ISSUE THREAD

**Issue by yidu-bjcancer** [RTKConsortium/RTK#313]
Freshly new hand at RTK/ITK. 
I followed the installation.md, downloaded ITK. During CMake compilation, I found that the Module_RTK is missing.

ITK: git clone yesterday
CMake: 3.10.0-rc1
Win10 + VS 2017

![WeChat Screenshot_20200228112239](https://user-images.githubusercontent.com/7495679/75507654-a7dbb780-5a1c-11ea-8e2d-de9127c0cef3.png)

**Comment by arobert01** [comment]
Hello,

With this commit https://github.com/InsightSoftwareConsortium/ITK/commit/b6ad2853de39734dd2427635949a88a398147df3 , ITK now provides ranking for all its remote modules. By default, only the Remote Modules with a minimum compliance level of 4 are shown in the CMake configuration. 

RTK compliance level is not yet specified and set to 1 by default. Then, to make Module_RTK appear in the CMake you have to set the ITK_MINIMUM_COMPLIANCE_LEVEL cmake variable to 1.

**Comment by SimonRit** [comment]
Thanks Antoine for pointing this out. @hjmjohnson, our [INSTALLATION.md](https://github.com/SimonRit/RTK/blob/master/INSTALLATION.md) is now obsolete! We have been doing our best to meet level 4, should we create a PR to let ITK developers decide if RTK is worth it?

**Comment by hjmjohnson** [comment]
Yes please!

**Comment by SimonRit** [comment]
I am looking into it but it seems that we cannot reach level 4 because we have only [71% code coverage](https://my.cdash.org/viewCoverage.php?buildid=1781635) instead of 75% required. I won't be able to fix this before March 9 (I'm on holidays). @hjmjohnson, can you confirm that the behavior observed on last night RTK dashboard, e.g., [here](https://my.cdash.org/viewConfigure.php?buildid=1781555), is the one expected, i.e., that you are no longer able to compile remote modules which don't reach level 4?

**Comment by hjmjohnson** [comment]
Simon,

 

This is something that we may need to fine tune as we may be too strict at the moment.  The default is currently ITK_MINIMUM_COMPLIANCE_LEVEL=4.

 

For your dashboard builds, can you please also set “-DITK_MINIMUM_COMPLIANCE_LEVEL:STRING=1”  (or whatever the necessary level for RTK is).

 

Sorry for the extra effort as we attempt to make the system for remote modules more robust.  Your feedback is very valuable.

 

Hans

**Comment by SimonRit** [comment]
I'll change ITK_MINIMUM_COMPLIANCE_LEVEL on our dashboard asap but I don't seem to be able to access our servers remotely so that may be in a few days...

**Comment by SimonRit** [comment]
FYI, I will modify RTK doc after InsightSoftwareConsortium/ITK#1675 is addressed.

**Comment by SimonRit** [comment]
InsightSoftwareConsortium/ITK#1675 has been addressed and it fixes this issue.
