### ISSUE TITLE
Unnecessary argument variable in CudaForwardProjectionImageFilter

### ISSUE THREAD

**Issue by kabcode** [RTKConsortium/RTK#316]
Hi,

i was looking though the code for the [rtkCudaForwardProjectionImageFilter](https://github.com/SimonRit/RTK/blob/master/src/rtkCudaForwardProjectionImageFilter.cu) but I do not recognize any use of the variable `dev_vol` as kernel argument.

**Has this variable some use in the kernel that is not provided by the texture object array `dev_tex_vol`?**
If not then `dev_vol` could be removed for maintainability.

**Comment by SimonRit** [comment]
Good catch, I think you're right and I have patched the code.
