### ISSUE TITLE
Unknown CMake command "WRAP_GGO".

### ISSUE THREAD

**Issue by jazb83** [RTKConsortium/RTK#325]
I am trying to build the example: rtkforwardprojections.cxx using CMAKE but I am getting this error:
"Unknown CMake command "WRAP_GGO"

OutPut: 

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
The C compiler identification is MSVC 19.16.27026.1
The CXX compiler identification is MSVC 19.16.27026.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (WRAP_GGO):
  Unknown CMake command "WRAP_GGO".

Configuring incomplete, errors occurred!
See also "G:/projects/forwarProjection/build/CMakeFiles/CMakeOutput.log".

This is my cmakefile:

# This is the root ITK CMakeLists file.
cmake_minimum_required(VERSION 3.10.2 FATAL_ERROR)
foreach(p
    ## Only policies introduced after the cmake_minimum_required
    ## version need to explicitly be set to NEW.
    CMP0070 #3.10.0 Define ``file(GENERATE)`` behavior for relative paths.
    CMP0071 #3.10.0 Let ``AUTOMOC`` and ``AUTOUIC`` process ``GENERATED`` files.
    )
  if(POLICY ${p})
    cmake_policy(SET ${p} NEW)
  endif()
endforeach()

# This project is designed to be built outside the Insight source tree.
# set(projectName RayTracing)
# set(targetName MyExe)
project(Test1)

WRAP_GGO(rtkforwardprojections_GGO_C rtkforwardprojections.ggo ../rtk3Doutputimage_section.ggo ${RTK_BINARY_DIR}/rtkVersion.ggo)

# Find ITK.
find_package(ITK REQUIRED)
include(${ITK_USE_FILE})

add_executable(rtkforwardprojections rtkforwardprojections.cxx ${rtkforwardprojections_GGO_C})
target_link_libraries(rtkforwardprojections ${ITK_LIBRARIES})

I built rtk as module of ITK (https://github.com/SimonRit/RTK/blob/master/INSTALLATION.md), but with CUDA OFF because I have CUDA 9.XXX and it gave a lot of error. So, I used RTK_USE_CUDA = OFF.

**Comment by SimonRit** [comment]
This example is not designed to be built outside the RTK tree. If you want to use gengetopt in a separate project, then you'll need to add `find_package(Gengetopt)` to your CMakeLists.txt.
