### ISSUE TITLE
cannot open file 'lpsolve55.lib'

### ISSUE THREAD

**Issue by mattiagrusio** [RTKConsortium/RTK#340]
LINK : fatal error LNK1104: cannot open file 'lpsolve55.lib'

I'm receiving this error from linker when compiling the example "FirstReconstruction".

Steps:
cmake config with use module RTK set to ON
cuda option off
building with Visual Studio 2017 x86
itk compilations gives no error

then I set ITK_DIR in the example project settings

lpsolve55.lib is present in the lib directoy of itk

Is there something I can do?

**Comment by SimonRit** [comment]
Can you try to change the GIT_TAG in [RTK.remote.cmake](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Remote/RTK.remote.cmake) file to master? cf77624 might help.

**Comment by mattiagrusio** [comment]
same error with GIT_TAG =master
any other ideas?

Thanks

**Comment by SimonRit** [comment]
Is it a Debug or Release compilation? Static or shared libs?

**Comment by mattiagrusio** [comment]
Debug and shared,
Thanks

Il Mar 21 Apr 2020, 22:02 Simon Rit <notifications@github.com> ha scritto:

**Comment by mattiagrusio** [comment]
Did not mention that I was using Qt Creator to build the project, with RTK module disabled it works.
If I enable RTK module and rebuild ITK i got the error lpsolve55.

I tried generating .sln file with Cmake GUI than opened with Visual studio and compilation/run works without errors.

So the problems seems to be related with how qt creator configure/generate cmake files.
Don't know why this came up only with RTK module.

Any suggestion are highly appreciated.

PS: About ITK compilation in my case it shows no errors even with RTK GIT_TAG = master
Thanks

**Comment by mattiagrusio** [comment]
The problems is the same if I open the example directory with Visual Studio (using "Open Folder").
Seems to be related to generator "ninja" which is default also in visual studio using cmake.
If I change generator to Visual Studio 2017 then it works.
If I select generator "Visual Studio 2017" in QtCreator then it fails in finding the correct build tools.

so the only way seems to generate the .sln file with cmake gui.

Thanks

**Comment by SimonRit** [comment]
I would suggest to compare the two CMakeCache.txt generated by the cmake gui and qt creator to see if there is a difference between the two.

**Comment by mattiagrusio** [comment]
The two CMakeCache where slightly different so : 
I configured QtCreator to use the same cmake configuration generated by cmake GUI (see attachments)
Then I selected Visual Studio 2017 as cmake generator in QtCreator (deleting the default "<undefined>" values of Platform and Toolset otherwise it doesn't work).
Last thing must change build target to ALL_BUILD instead of all.
with this configuration it works with no issues also with Qt Creator

I'm attaching two different cmakecache the *_Visual Studio 2017 version compiles correctly the *_Ninja don't.

![build steps](https://user-images.githubusercontent.com/10075606/80101701-1008ce80-8572-11ea-8c11-08542e18e5d3.jpg)
[CMakeCache_Ninja.txt](https://github.com/SimonRit/RTK/files/4522587/CMakeCache_Ninja.txt)
[CMakeCache_Visual Studio 2017.txt](https://github.com/SimonRit/RTK/files/4522588/CMakeCache_Visual.Studio.2017.txt)
![Generator](https://user-images.githubusercontent.com/10075606/80101706-1139fb80-8572-11ea-8b70-131b505900cd.jpg)
