### ISSUE TITLE
Iteration count is not reset between executions

### ISSUE THREAD

**Issue by acoussat** [RTKConsortium/RTK#357]
1. Create an iterative filter and set a `VerboseIterationCommand` callback, i.e.
```cpp
using VerboseIterationCommandType = rtk::VerboseIterationCommand<FilterType>;
typename VerboseIterationCommandType::Pointer verboseIterationCommand = VerboseIterationCommandType::New();
filter->AddObserver(itk::IterationEvent(), verboseIterationCommand);
```
2. Call `filter->Update()` several times.
3. Iteration count is not reset between executions.

Expected behavior: iteration count should be reset at the beginning of each execution.

Looking at how this feature is written, I don't see an obvious fix.

**Comment by SimonRit** [comment]
It's not even obvious that it should always be reset automatically. There are scenarios where you want to do 10 iterations with a parameter (e.g. regularization), then modify it and continue the iterations.

**Comment by acoussat** [comment]
I hadn't thought of that. Should we therefore leave it as is, or do you see something to be improved here?

**Comment by SimonRit** [comment]
I'm closing it. If someone is bothered by this, he should keep track of the value returned by `AddObserver`, and remove it with `RemoveObserver` + creating a new one. It is however safer to create a new filter for a new reconstruction in case the iterations store intermediate variables (like the conjugate gradient or the nesterov momentum). Thanks @acoussat!
