### ISSUE TITLE
Cuda enforces float image

### ISSUE THREAD

**Issue by finetjul** [RTKConsortium/RTK#367]
I have unsigned short projection images, but rtkfdk.exe enforces a float output volume (see [CudaDisplacedDetectorImageFilter](https://github.com/SimonRit/RTK/blob/master/include/rtkCudaDisplacedDetectorImageFilter.h)). Why so ? Couldn't it be template ?

Some context: when my output volume gets somewhat large (e.g. 1024x1024x1024), I have a CUDA out of memory error before starting reconstruction. Playing with lowmem or subsetsize does not help.

Any idea ?

**Comment by SimonRit** [comment]
It could be templated but that's not straightforward, you need to template the Cuda kernel (in the first Cuda versions we used, it was really dificult, it's easier now I believe). Then, for integers, there is the difficulty of the effect of numerical errors and it's clearly something we have not worked on.

You should however be able to handle all this with streaming though. Have you tried the `--divisions` option?

**Comment by finetjul** [comment]
Thanks for the info. I'm closing it for now then.
