### ISSUE TITLE
How to use your own dataset for reconstruction

### ISSUE THREAD

**Issue by shaleenanuj** [RTKConsortium/RTK#368]
Hello

I have a set of projection images, how to use them to get the reconstructed slides using rtk in python?
Can I get an example of doing it?

Please let me know.

Thanking you in advance.
Regards,
Shaleen

**Comment by SimonRit** [comment]
This is not an issue, please use the mailing list rtk-users@openrtk.org. Check the wiki examples [here](http://wiki.openrtk.org/index.php/RTK_wiki_help#Applications).
