### ISSUE TITLE
Recover Hounsfield units 

### ISSUE THREAD

**Issue by finetjul** [RTKConsortium/RTK#369]
In addition to projection 2D slices, I have an`air` 2D slice  and a `dark` 2D slice. How can I use such extra information ? I tried to average those pixel values and feed `airthres` and `idark` parameters with no luck (output pixels range from -0.014 to 0.34)

How can I have hounsfield units back in the reconstructed volume ?

**Comment by SimonRit** [comment]
In regular polychromatic x-ray CT, you need a calibration scan, with air and water. You segment an air region and a water region, calculate the average value in each region and apply a linear scaling of the reconstructing values to put air at -1000 and water at 0, which I think you can achieve with itk::IntensityWindowingImageFilter.
The reconstructed values are in inverse length but since it polychromatic, it's hard to relate to a given energy.

**Comment by finetjul** [comment]
For the records, I converted my projection volume to `unsigned short` (instead of short) and I used the median pixel value in the `air` image as `i0` parameter, and the median pixel value in the `dark` image as `iDark` parameter. Therefore rtk::LUTbasedVariableI0RawToAttenuationImageFilter got used to convert my RAW image (white pixels mean air) into an Attenuation image (black pixels mean air).
For `itk::ShiftScaleImageFilter`, I compute `scale` and `shift` from: 1) the mapping of air (i.e. 0.0 in reconstructed volume, -1000 in Hounsfield Unit)  and 2) in a reconstructed phantom I find water value (0 in Hounsfield Unit)

**Comment by SimonRit** [comment]
Sounds good, thanks for sharing.

**Comment by finetjul** [comment]
Actually,`LUTbasedVariableI0RawToAttenuationImageFilter` does not work on some images with metal in it.

I found in RTK 3 ways to convert from RAW to Attenuation:
 - XRad: ```-log(max(0, (input - dark) / (flat - dark))```
 - EDF: ```-log( (input - dark) / (ref - dark))```
 - LUT: ```log (max(1, I0 - dark)) - log(max(1, input - dark)) ~= -log(max(1, (input - dark) / (I0 - dark)))```

It is not clear to me if `flat` (in `rtk::XRadRawToAttenuationToImageFilter`) and `ref` (in `rtk::EDFAttenuationToImageFilter`) are the same as `I0` in `rtk::LUTbasedVariableI0RawToAttenuationImageFilter`.

How can we guess what conversion to apply between XRad, EDF and LUT on RAW images we do not know how they were acquired. @SimonRit, any idea ?

**Comment by SimonRit** [comment]
Thanks for the code review! Yes, I0, flat and ref are the measured values without object. However, LUT assumes that this is constant over the projections whereas xrad and edf provide a projection without object if I remember correctly. You could measure one projection without object to know what to use. You can also guess the value in air using [I0EstimationProjectionFilter](http://www.openrtk.org/Doxygen/classrtk_1_1I0EstimationProjectionFilter.html).
The problem with metal is photon starvation. The Beer Lambert law assumes that some photons pass through the object. If their number is equal (or below) the dark value (projection with x-ray beam off), then it will take the log of 0. This is why LUT takes the max. A wrong dark value will cause similar problems.
