### ISSUE TITLE
what is CUDA_wrap

### ISSUE THREAD

**Issue by 1939938853** [RTKConsortium/RTK#373]
Hello,

What is CUDA_wrap? Where to get it? What is the version requirement?

Thank you very much!

**Comment by SimonRit** [comment]
CUDA_wrap is a wrapping of the CUDA cmake module. It is based on a [plastimatch file](https://gitlab.com/plastimatch/plastimatch/-/blob/master/cmake/FindCUDA_wrap.cmake). Normally, you don't need to know where to find it, cmake should automatically install it and configure the cmake path. The file is available [here](https://github.com/SimonRit/RTK/blob/master/cmake/FindCUDA_wrap.cmake).
