### ISSUE TITLE
RTK incompatible with CUDA 11

### ISSUE THREAD

**Issue by MrTzschr** [RTKConsortium/RTK#381]
Hi,

I tried to compile RTK as a module of ITK 5.1.1 using CUDA Toolkit 11.1.0 on Windows 10 using CMake 3.17.4 and Visual Studio 2019 v16.7.5.
This fails with the following error:
```
>------ Erstellen gestartet: Projekt: RTK, Konfiguration: Release x64 ------
>Generating ../../itkFunctionBase.xml
>Building NVCC (Device) object Modules/Remote/RTK/src/CMakeFiles/cuda_compile_1.dir/Release/cuda_compile_1_generated_rtkCudaAverageOutOfROIImageFilter.cu.obj
>nvcc fatal   : Unsupported gpu architecture 'compute_30'
>CMake Error at cuda_compile_1_generated_rtkCudaAverageOutOfROIImageFilter.cu.obj.Release.cmake:220 (message):
>  Error generating
>  C:/[...]/ITK-5.1.1-bin/Modules/Remote/RTK/src/CMakeFiles/cuda_compile_1.dir//Release/cuda_compile_1_generated_rtkCudaAverageOutOfROIImageFilter.cu.obj
```

Looking at the corresponding ```NVCC_CUDA_FLAGS``` inherited from [here](https://github.com/SimonRit/RTK/blob/019b327d2fd26d97e61b43c4cd6167e04807b573/cmake/FindCUDA_wrap.cmake#L62):
```
set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS}
     -gencode arch=compute_30,code=sm_30
     -gencode arch=compute_35,code=sm_35
     -gencode arch=compute_35,code=compute_35
    )
````
I see that compute capability (CC) 3.0 is required at minimum.
However, the minimum CC for CUDA 11 is 3.5 as of [this link](https://stackoverflow.com/a/28933055) - I couldn't find any official/better statement, sorry.
I have not tried to change anything because I cannot foresee the effects.

Best,
Moritz

**Comment by SimonRit** [comment]
That should not be hard to fix, it's a regular issue, see code [here](https://github.com/SimonRit/RTK/blob/master/cmake/FindCUDA_wrap.cmake#L45-L66). I'll suggest a fix next week if you haven't suggested one by then.

**Comment by SimonRit** [comment]
Can you review #385 please?

**Comment by MrTzschr** [comment]
Thanks for the update.
I will look into it. Sadly, I cannot update my productive system to CUDA 11 right now, so this will take a bit of time.

**Comment by SimonRit** [comment]
I have merged (and therefore closed), just reopen if you notice something wrong when you merge. It will also be tested on different CUDA versions overnight.

**Comment by MrTzschr** [comment]
#385 compiles for me without errors.
I just get a lot more `was declared deprecated` warnings, see [this list](https://docs.nvidia.com/cuda/cuda-runtime-api/deprecated.html). Older releases just raised warnings due to usage of `cuda_runtime.h`.
Looks like a bit of rework is necessary in the future.

**Comment by SimonRit** [comment]
Sorry I missed that, thanks for pointing it out. I have opened #386 as a reminder.
