### ISSUE TITLE
KWStyle fails in rtk::ComputeAttenuationCorrectionBackProjection

### ISSUE THREAD

**Issue by SimonRit** [RTKConsortium/RTK#382]
[`m_ex1`](https://github.com/SimonRit/RTK/blob/master/include/rtkJosephBackAttenuatedProjectionImageFilter.h#L141) is not an accepted name for ITK members. I would correct it if I knew what is the proper name... If this is the article name, use m_Ex1, that should pass kwstyle (checked at commit time now). @arobert01, can you handle this or let me know where this name comes from?

**Comment by arobert01** [comment]
Yes indeed, I used the notations from the article for naming the variables. Do you want me to rename it to m_Ex1 ?

**Comment by SimonRit** [comment]
Thanks, I'll handle it. There are a few other errors that popped up, I'll fix them altogether.
