### ISSUE TITLE
Reconstruction fails with circular projection geometry does not describe a full circle

### ISSUE THREAD

**Issue by ClementMirabel** [RTKConsortium/RTK#394]
Hi,

I have been trying to set the geometry in ThreeDCircularProjectionGeometry with values between 0 and 180 degrees, to reproduce the motion of some acquisition systems, but reconstruction always fails when the values do not reach max value of 360.

My workflow is the following :
- Apply JosephForwardProjectionImageFilter on a 3D Volume
- Do RayEllipsoidIntersectionImageFilter or ParkerShortScanImageFilter
- Try to reconstruct using FDKConeBeamReconstructionFilter

Although, the result from JosephForwardProjectionImageFilter describes a 180 degrees rotation, so the issue does not seem related to the forward projection but only the reconstruction (modulo some pre-processing).

**Comment by SimonRit** [comment]
Prefer the mailing list rtk-users@openrtk.org until we are confident this is an issue, i.e., a problem with RTK code. Can you explain why you use RayEllipsoidIntersectionImageFilter in your pipeline? Can you describe what "fails" means to you? Can you provide the geometry file? Thanks!
