### ISSUE TITLE
RTK keeps absolute paths to source/build location when ITK is installed

### ISSUE THREAD

**Issue by codeling** [RTKConsortium/RTK#399]
I have built ITK 5.1.2 from source (let's say sources in `/home/codeling/devel/itk/source`, build in `/home/codeling/devel/itk/build`), enabled the RTK module in it (with default version 2.1.0), and then I installed the ITK library (let's say to `/opt/itk`).
I noticed that my application linking to this installed ITK (in `/opt/itk`) still was referencing a path from where the build was done (`/home/codeling/devel/itk/build` and `/home/codeling/devel/itk/source`).

Searching the generated ITK cmake config in `/opt/itk/lib/cmake/ITK-5.1`, I found the RTK library to be the culprit - the Modules/RTK.cmake contains hard-coded build/source paths in RTK_INCLUDE_DIRS and RTK_LIBRARY_DIRS.

Checking the `includes` subdirectory, it contains an RTK subdirectory, but not all the files that are referenced in the INCLUDE__DIRS are there.
```
set(RTK_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.1;/home/codeling/devel/itk/source/Modules/Remote/RTK/utilities/lp_solve;/home/codeling/devel/itk/source/Modules/Remote/RTK/utilities/lp_solve/shared;/home/codeling/devel/itk/source/Modules/Remote/RTK/utilities/lp_solve/bfp;/home/codeling/devel/itk/source/Modules/Remote/RTK/utilities/lp_solve/bfp/bfp_LUSOL;/home/codeling/devel/itk/source/Modules/Remote/RTK/utilities/lp_solve/bfp/bfp_LUSOL/LUSOL;/home/codeling/devel/itk/source/Modules/Remote/RTK/utilities/lp_solve/colamd;/workspace/itk/bin-5.1.2/Modules/Remote/RTK")
```
(there is a folder `lp_solve`, but no subfolders).

And the LIBRARY_DIRS just plainly point to the build directory:
```
set(RTK_LIBRARY_DIRS "/home/codeling/devel/itk/build/lib")
```

Is installation just not implemented yet for RTK?

**Comment by codeling** [comment]
I'm currently trying a workaround: 
  - copying all headers from `/home/codeling/devel/itk/source/Modules/Remote/RTK/utilities/lp_solve` to `/opt/itk/includes/RTK/lpsolve`
  -  replacing all `/home/codeling/devel/itk/source/Modules/Remote/RTK/utilities/lp_solve` in `RTK_INCLUDE_DIRS` with `${ITK_INSTALL_PREFIX}/include/RTK/lpsolve`
  -  adapting the RTK_LIBRARY_DIRS to `${ITK_INSTALL_PREFIX}/lib`

And it seems to be working.... so if these things could be done during ITK installation, that would be great! If I have time I'll look into it myself but not knowing RTK's structure, this could take a while.

**Comment by SimonRit** [comment]
Thanks for reporting this. We'll try to work in our side. cc @LucasGandel
