### ISSUE TITLE
Can not reconstruct with raw data[data type is unsigned short]

### ISSUE THREAD

**Issue by xqzhaoxh** [RTKConsortium/RTK#402]
When I perform reconstruction, encounter the following error:
......
Ignoring file: E:/RawData/raw.0357
Ignoring file: E:/RawData/raw.0358
Ignoring file: E:/RawData/raw.0359
ExceptionObject caught with reader->UpdateOutputInformation() in file c:\opensourcelibrary\itk-5.1.0\include\itk-5.1\rtkggofunctions.h line 273

itk::ExceptionObject (000000C54091B338)
Location: "void __cdecl rtk::ProjectionsReader<class itk::CudaImage<float,3> >::GenerateOutputInformation(void)"
File: c:\opensourcelibrary\itk-5.1.0\include\itk-5.1\rtkprojectionsreader.hxx
Line: 160
Description: itk::ERROR: Cannot create ImageIOFactory for file E:/RawData/raw.0000

**Comment by SimonRit** [comment]
Yes, ITK does not recognize raw data file format. You need to convert it to a known file format, e.g., by creating a mhd header in the MetaIO format.

**Comment by xqzhaoxh** [comment]
THANDS
