### ISSUE TITLE
No module named 'itkHelpers'

### ISSUE THREAD

**Issue by adrienler** [RTKConsortium/RTK#422]
Hello,

I'm new to RTK. I recently installed itk-rtk Python package using Anaconda :
`pip install itk-rtk` 

which is the RTK 2.2.0 version, if I'm not wrong. 

Installing has been successful. Nevertheless, an error occurs executing the following code :

`import itk`
`from itk import RTK as rtk`
`geometry = rtk.ThreeDCircularProjectionGeometry.New()`

Resulting in :

`ModuleNotFoundError: No module named 'itkHelpers'`

I found similar issues for old versions, but not for the latest one.

Thanks for your help,

Adrien

**Comment by SimonRit** [comment]
ITK recently released new packages and RTK needs to be updated. Until this is fixed, you an use a previous version:
```
pip install itk==5.1.2 itk-rtk --force-reinstall
```
I'll let you know when there is a solution to use the latest ITK.

**Comment by adrienler** [comment]
Thank you for the quick and accurate answer, it works.

**Comment by SimonRit** [comment]
Great but let's keep it opened until it's been really fixed...

**Comment by SimonRit** [comment]
To use the latest ITK, you can download packages compiled by the CI until a new RTK version is released, e.g., [here](https://github.com/SimonRit/RTK/actions/runs/925499084).
