### ISSUE TITLE
“itkRTK-5.2.lib” is not created

### ISSUE THREAD

**Issue by Truring** [RTKConsortium/RTK#424]
Thanks for your great work! 
I build RTK with VS 2017. But there is no “itkRTK-5.2.lib” in the folder "lib/debug". How to make this lib?
![image](https://user-images.githubusercontent.com/22017747/125250671-1f1b9e00-e329-11eb-82b9-0c21190d5d41.png)

**Comment by SimonRit** [comment]
It seems that you have not compiled RTK, see https://github.com/SimonRit/RTK/blob/master/INSTALLATION.md. Prefer using the mailing list for such questions, rtk-users@openrtk.org, we use the github issues for reporting bugs.

**Comment by Truring** [comment]
Sorry for bothering you. I followed the instructions from&nbsp;RTK/INSTALLATION.md at master · SimonRit/RTK (github.com), but I still got caught by this problem. And there are only "ITKCudaCommon.lib" and "lpsolve55.lib" in the folder "../../lib/Debug/".








Best Wishes,
Truring







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SimonRit/RTK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SimonRit/RTK] “itkRTK-5.2.lib” is not created (#424)





 
It seems that you have not compiled RTK, see https://github.com/SimonRit/RTK/blob/master/INSTALLATION.md. Prefer using the mailing list for such questions, ***@***.***, we use the github issues for reporting bugs.

**Comment by SimonRit** [comment]
Do you have any error during the RTK compilation? What version of RTK and
MSVC are you using?

**Comment by Truring** [comment]
I use Visual Studio 2017 Community，version 15.9.13，MSVC++ 14. 
I first compile ITK 5.2.0 with "Module_RTK = off". Then I compile RTK-2.2.0 independently. The Cmake process is ok, but I fail to build the RTK.sln with VS2017. And there is no "itkRTK-5.2.lib" produced.

**Comment by Truring** [comment]
![image](https://user-images.githubusercontent.com/22017747/125419477-8958c4f3-df62-4bfd-bc8b-0eb055a3885f.png)
![image](https://user-images.githubusercontent.com/22017747/125419499-23ef409f-5e6d-47b1-a723-fc55f9e88c15.png)

**Comment by SimonRit** [comment]
If you fail to build RTK.sl, then itkRTK-5.2.lib is not produced. There's
been a problem with the latest ITK release regarding cmake version (see here
<https://github.com/SimonRit/RTK/issues/419>), try building against the
release branch of ITK's github.

**Comment by Truring** [comment]
Thank you very much. I redownload the RTK and ITK with your suggestions. And now both ITK and RTK can work well.
