### ISSUE TITLE
How to convert NIFTI or DICOM images into 3D mesh by using RTK?

### ISSUE THREAD

**Issue by Truring** [RTKConsortium/RTK#425]
Hello, I'm using RTK for spine reconstruction. I have some spine segmentation images in NIFTI format, how can I use RTK to reconstruct 3D spine mesh from these segmentation nifti images?
![image](https://user-images.githubusercontent.com/22017747/125548012-adfa6c14-762b-4405-a695-da8d6330540d.png)

**Comment by SimonRit** [comment]
It's not possible, you probably need to go to ITK or VTK. And in any case, this is not an issue (see my answer to #425), don't post your questions here.
