### ISSUE TITLE
first recon example can't be run 

### ISSUE THREAD

**Issue by wangdongping74** [RTKConsortium/RTK#436]
![image](https://user-images.githubusercontent.com/16449811/133396129-2076e416-d872-49f5-ba36-7f646e03dea9.png)

when i run the example without cuda, i found this error:
no module named "itkTemplate"ModuleNotFoundError                      

 Traceback (most recent call last)
C:\Users\WANGDO~1\AppData\Local\Temp/ipykernel_25436/1991000702.py in <module>
----> 1 geometry = rtk.ThreeDCircularProjectionGeometry.New()

~\Anaconda3\envs\env_rtk\lib\site-packages\itk\rtkThreeDCircularProjectionGeometryPython.py in New(*args, **kargs)
    162         """
    163         obj = rtkThreeDCircularProjectionGeometry.__New_orig__()
--> 164         import itkTemplate
    165         itkTemplate.New(obj, *args, **kargs)
    166         return obj

ModuleNotFoundError: No module named 'itkTemplate'

**Comment by SimonRit** [comment]
The current packages on pypi have been built with a previous version of ITK. Can you try with the CI packages if it works better? You can download the latest packages from [here](https://github.com/SimonRit/RTK/actions/runs/1228321753) if you're logged in github.

**Comment by wangdongping74** [comment]
thank you.
it looks it works.

![image](https://user-images.githubusercontent.com/16449811/133550735-8bcbe5aa-0f38-46a3-ae9e-c099ec3a3fe8.png)

**Comment by SimonRit** [comment]
Thanks for the report.
