### ISSUE TITLE
Enabling RTK_USE_CUDA causes CUDA dependency in all ITK libraries, even on non-RTK-related libraries

### ISSUE THREAD

**Issue by codeling** [RTKConsortium/RTK#438]
When I build ITK with Module_RTK enabled, and RTK_USE_CUDA enabled, the resulting ITK build forces a CUDA dependency on all consuming applications/libraries (even if only referencing ITK libraries that don't have anything to do with RTK).

In CMake, I get errors such as this:
 ```
CMake Error at gui/CMakeLists.txt:6 (add_executable):
  Target "mytarget" links to target "CUDA::cufft" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

Is this a well-known issue? Is there a workaround (apart from finding the CUDA package and linking it to all applications/libraries that use this ITK build)? I would expect that I only get the CUDA dependency if I actually use RTK - why would the CUDA dependency be "inherited" upwards from RTK?
This can make things a bit tedious - the ITK libraries "tainted" by RTK with CUDA can only be used with the whole CUDA package; meaning that such a build can only be used on machines with an nvidia card - even the parts not using RTK at all (imagine e.g. the parts using RTK being optional, only used in shared libraries that are dynamically loaded)
The only "workaround" which I see at the moment, is to have multiple separate ITK builds (i.e. at least one with and one without RTK/CUDA, and using the RTK/CUDA build only if absolutely necessary).

**Comment by SimonRit** [comment]
I don't know if this is the expected behavior. Maybe someone more expert would know? @dzenanz @thewtex @LucasGandel

**Comment by codeling** [comment]
Maybe something else apart from RTK is also using CUDA if available? I do have ITK_USE_GPU enabled on that build too, but mainly for OpenCL-enabled filters. I don't see any CMake option to disable CUDA for something else than RTK though...

Oh - I guess this is due to me adding RTK to the components requested from ITK in our find_package call - so no wonder it gets a dependency. I think I should rethink our CMake scripts in that regard... adding a specific find_package for ITK for the libraries that actually use RTK or something like that; I guess it would be easier if ITK would support separate linking to libraries, instead of the ITK_USE_FILE, though.... anyway, I think nothing to be specifically done here immediately, sorry for the noise!
