### ISSUE TITLE
rtkPython can handle varain .hnd files?

### ISSUE THREAD

**Issue by shun-otsuka** [RTKConsortium/RTK#441]
rtkPython can handle varain .hnd files?

Hi, Mr.Simon
Thanks to Mr.Simon and your team for creating this amazing program.

I have just started ITK and RTK in Python.
I want to make a new effort using the projection data varian's OBI(CBCT).
I need to handle varian .hnd files for that purpose.
I tried a few, but it didn't succeed.
rtkPython can handle varain .hnd files?
The .hnd file is downloaded from the link below.
https://wiki.openrtk.org/index.php/RTK/Examples/VarianReconstruction

I look forward to your reply.

**Comment by SimonRit** [comment]
Please use the mailing list for such questions, rtk-users@openrtk.org, or http://discourse.itk.org, this is is not an RTK issue. This has been discussed on [discourse](https://discourse.itk.org/t/io-in-python-module/2846) before. For Hnd, the code would look like this
```
import itk
imageio = itk.HndImageIO.New()
image = itk.imread("raw.hnd", imageio=imageio)
```

**Comment by shun-otsuka** [comment]
It is successful.
I am very grateful to you.
