### ISSUE TITLE
Option --costs does not work in rtkcongugategradient

### ISSUE THREAD

**Issue by m-mouchet** [RTKConsortium/RTK#448]
Looking at the file rtkConjugateGrandientImageFilter.hxx, m_ResidualCosts seems never updated.

**Comment by acoussat** [comment]
After some research in the git history, @arobert01 and I found that
- commit 0e004962 commented out the code that computes `m_ResidualCosts`;
- commit cac3e23c1e5ed5e76fc1efe0054cf4bc345f7e7d seems to remove the commented code.

@SimonRit @cyrilmory, any idea of what happened?
