### ISSUE TITLE
In example FirstCudaReconstruction.py, cannot import name 'rtk' from 'itk'

### ISSUE THREAD

**Issue by 17852739584** [RTKConsortium/RTK#457]
Hello, I'm a beginner of RTK. When I am ready to run the sample program in Python3.7, the IDE prompts: cannot import name 'RTK' from 'ITK'. I have installed itk5.2.1 through PIP in advance. How to deal with this situation? Thank you again.
——————
import sys
import itk
from itk import **rtk** as rtk
——————
Traceback (most recent call last):
  File "D:/Backup/Downloads/RTK-2.3.0/RTK-2.3.0/examples/FirstReconstruction/FirstCudaReconstruction.py", line 4, in <module>
    from itk import rtk as rtk
ImportError: cannot import name 'rtk' from 'itk' (E:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\itk\__init__.py)
——————

**Comment by SimonRit** [comment]
You first need to install `itk-rtk`, see [INSTALLATION.md](https://github.com/SimonRit/RTK/blob/master/INSTALLATION.md). The distributed binary packages on pypi do not have the Cuda part, to have access to this you'll need to compile the package yourself.
