### ISSUE TITLE
geometry & origin specifications

### ISSUE THREAD

**Issue by grupesh** [RTKConsortium/RTK#497]
Hi all,
I'm trying to match my scanner geometry to RTK geometry using the document (http://www.openrtk.org/Doxygen/DocGeo3D.html)
![image](https://user-images.githubusercontent.com/61022872/172419763-f0d359c0-93e4-45a4-b5b0-88db69b24f35.png)
In my translation, isocenter corresponds to center of rotation and detector origin corresponds to geometric center of detector. Is that right? I've defined the offsets and distances with this assumption.

With this assumption, what should be origin of 3D volume and projection stack in python code? Are those (0,0,0) or negative/positive of volume shape divided by 2?

After defining geometry, I'm trying to forward project our scanner reconstructed volume and see if projections make sense.

**Comment by SimonRit** [comment]
Please use the [mailing list](https://public.kitware.com/mailman/listinfo/rtk-users) for these questions. In a regular geometry, all offsets are set to 0, isocenter is at (0,0,0) and the origin of the coordinate system of the detector ("Det. Origin") is at (0,0). The `m_Origin` of the images is something different, it only indicates the coordinate of the first voxel / pixel of the images. If your volume is centered around (0,0,0) (the isocenter/center of rotation), then it should be volume shape divided by 2, and the same for the detector.
