### ISSUE TITLE
FDKConeBeamReconstructionFilter went wrong with large crop in the 3rd dimension of the input image

### ISSUE THREAD

**Issue by theysp** [RTKConsortium/RTK#498]
if set large crop to the input image and generate input image with index from (x,y,z) where z is larger than 15,  exception would be thrown in line 130 of file "[RTK](https://github.com/SimonRit/RTK/tree/v2.3.0)/[include](https://github.com/SimonRit/RTK/tree/v2.3.0/include)/rtkFDKConeBeamReconstructionFilter.hxx".
 

This is caused by the code error of setting the index of subregion of batch 1, where the index of subregion is set to (x, y, i), according to the default value of m_ProjectionSubsetSize, when batch 1 reaches, i would be 16, which would trigger exception throwing,  when the crop of the 3rd dimension is set to value larger than 15.

I am sorry for the confused description. Let me get things together.
1. I organize all the projections in a 3D image in **_itk::Image<float, 3>_**;
2. I used **_itk::CropImageFIlter_**, and set the **_lowerBoundaryCropSize_** as [4,4,50], and set the _**UpperBoundaryCropSize**_ as [4,4,50], for I want to ignore the 50 projections at the beginning of the scan. 
3. I feed the cropped projections to the rtk::FDKConeBeamReconstructor, it went wrong when the code run into line 130:
"_m_BackProjectionFilter->GetOutput()->PropagateRequestedRegion();_"
Because the above lines set the **_subsetRegion_** without considering the valid region of the cropped projections.

I hope it is easier to follow. And I am sorry it is so difficult for me to create a reproducible example, because all my code lives in a remote driver not connected to the internet.

**Comment by theysp** [comment]
I was using 2.1.0, and I have checked it is not changed in 2.3.0. By the way, all reconstruction filters including the CUDA implementations have the same issue.

I am sorry that I am not getting used to git to commit the fixed code. It would be great that you guys get it done.

**Comment by SimonRit** [comment]
Can you produce a reproducible example to understand the issue? Your description is a quite difficult to follow...

**Comment by theysp** [comment]
I am sorry for the confused description. Let me get things together.
1. I organize all the projections in a 3D image in **_itk::Image<float, 3>_**;
2. I used **_itk::CropImageFIlter_**, and set the **_lowerBoundaryCropSize_** as [4,4,50], and set the _**UpperBoundaryCropSize**_ as [4,4,50], for I want to ignore the 50 projections at the beginning of the scan. 
3. I feed the cropped projections to the rtk::FDKConeBeamReconstructor, it went wrong when the code run into line 130:
"_m_BackProjectionFilter->GetOutput()->PropagateRequestedRegion();_"
Because the above lines set the **_subsetRegion_** without considering the valid region of the cropped projections.

I hope it is easier to follow.

**Comment by SimonRit** [comment]
I'm not surprised that this is not working because the index of the projection (third dimension) is not starting at 0 and I am pretty sure it has not been considered in many parts of the code. My advice for doing this is to create a new stack (e.g. with [rtksubselect](https://github.com/SimonRit/RTK/tree/master/applications/rtksubselect)) and to use this new stack and the associated new geometry.

**Comment by theysp** [comment]
Thanks
