### ISSUE TITLE
run FirstReconstruction.cxx

### ISSUE THREAD

**Issue by xsk0802** [RTKConsortium/RTK#512]
Hello, teacher. I want to run the /examples/FirstReconstruction/FirstReconstruction.cxx file. How do I run this routine

**Comment by SimonRit** [comment]
You need to install RTK first (see [INSTALLATION.md](https://github.com/SimonRit/RTK/blob/master/INSTALLATION.md)) and then you should be able to compile it with CMake.

**Comment by xsk0802** [comment]
Whether to input parameters when running FirstReconstruction.cxx, I execute FirstReconstruction.cxx After cxx, only Usage: FirstReconstruction<outputimage><outputgeometry>is displayed Or if it is convenient for you to send me a corresponding FirstReconstruction.exe file

**Comment by SimonRit** [comment]
You have to pass the parameters on the command line. If you want a pre-compiled version, you can use the python version from pypi.

**Comment by xsk0802** [comment]
What parameters are entered?

**Comment by SimonRit** [comment]
The usage explains it
```
Usage: FirstReconstruction <outputimage> <outputgeometry>
```
The first is an output image file name, e.g. `a.mha`, and the second a geometry file name, e.g. `a.xml`.
