### ISSUE TITLE
run rtkmotioncompensateddfdktest.cxx

### ISSUE THREAD

**Issue by xsk0802** [RTKConsortium/RTK#513]
Hello, teacher. I'm trying to run rtkmotioncompensateddfdktest.cxx, but there are many environment configurations. Do you have any reference configuration process or operation steps.

**Comment by SimonRit** [comment]
See https://wiki.openrtk.org/index.php/RTK/Examples/MCCBCTReconstruction. Please stop using github issues when it is not a code issue. You can use the [mailing list](https://public.kitware.com/mailman/listinfo/rtk-users) for the questions.
