### ISSUE TITLE
 Unknown CMake command "itk_module_test"

### ISSUE THREAD

**Issue by xsk0802** [RTKConsortium/RTK#514]
I am trying to build the example: rtkmotioncompensateddfdktest.cxx using CMAKE but I am getting this error:

CMake Error at CMakeLists.txt:43 (itk_module_test):
  Unknown CMake command "itk_module_test".
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as
    cmake_minimum_required(VERSION 3.25)

**Comment by SimonRit** [comment]
This is not an example, this is a test. You need to build RTK with the CMake option `BUILD_TESTING` `ON` to compile it. It think you should spend time on the [ITK software guide](https://itk.org/ITKSoftwareGuide/html/) to better understand RTK.
