### ISSUE TITLE
Code cleaning and modernization conformance with ITK

### ISSUE THREAD

**Issue by hjmjohnson** [RTKConsortium/RTK#52]
@SimonRit @dsarrut @jjomier @gregsharp @nocnokneo 

As I have been reviewing the RTK code, I recognized that it could be modernized a bit to conform more closely with ITK.

In particular, when compiling with C++11 support, there are some newer ITK paradigms that allow for more strict testing.

Please consider these patches for inclusion.

Regards,
Hans

**Comment by SimonRit** [comment]
Dear Hans,
May I also close this issue? I applied most of the patches I think.
Thanks,
Simon

**Comment by hjmjohnson** [comment]
@SimonRit Thank you.  I'll close.

Hans
