### ISSUE TITLE
data loss in volume when reconstructing a anisotropic voxel

### ISSUE THREAD

**Issue by baladastagiri14** [RTKConsortium/RTK#542]
Hi all, 

   ConstantImageSourceType::Pointer outVol=ConstantImageSourceType::New();
    ConstantImageSourceType::PointType origin_out;
    ConstantImageSourceType::SizeType size_out;
    ConstantImageSourceType::SpacingType spacing_out;
    size_out[0] = ctDIM1;// 512
    size_out[1] = ctDIM3;//120
    size_out[2] = ctDIM2;//512
    spacing_out[0] = 0.4238;
    spacing_out[1] = 1;
    spacing_out[2] = 0.4238;

    origin_out[0] = -0.5*(size_out[0]-1)*(spacing_out[0]);
    origin_out[1] = -0.5*(size_out[1]-1)*(spacing_out[1]);
    origin_out[2] = -0.5*(size_out[2]-1)*(spacing_out[2]);
    outVol->SetOrigin(origin_out);
    outVol->SetSpacing(spacing_out);
    outVol->SetSize(size_out);
    outVol->SetConstant(0);

When i tried to reconstruct a anisotropic voxel there is loss of data in the top & bottom portion of volume and  the same doesnt happen if i try to reconstruct it with equal spacing out in all three direction

could you please help me out to figure out this issue 

I have attached two images with same pixelspacing and variable pixelspacing for your reference,

![samepixel](https://user-images.githubusercontent.com/130033983/230290965-5ed2b90e-c2ef-47ea-9db6-efbeadbf1aa7.PNG)
![vaiablepixelspac](https://user-images.githubusercontent.com/130033983/230290996-14c0c973-5557-403b-bc35-a1ca3a6d8a8d.PNG)

**Comment by SimonRit** [comment]
Please address user questions to the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users), this is not an issue.
