### ISSUE TITLE
run FirstCudaReconstruction.cxx , CudaFDKConeBeamReconstructionFilter  Update() error

### ISSUE THREAD

**Issue by loufear** [RTKConsortium/RTK#546]
ProcessObject::Update()
{
  if (this->GetPrimaryOutput())
  {
    this->GetPrimaryOutput()->Update();
  }
}
first stack error

**Comment by loufear** [comment]
cuda 11.4 verson

**Comment by loufear** [comment]
the cpu version FirstReconstruction.cxx also error  please give me some suggestions

**Comment by SimonRit** [comment]
We don't know what is the error (launch time? compilation time? what message?). This is not the right location for a user issue, please use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users).
