### ISSUE TITLE
RTK does not compile with CUDA 12

### ISSUE THREAD

**Issue by SimonRit** [RTKConsortium/RTK#549]
https://discourse.itk.org/t/about-gpu-version-compilation-of-rtk/5905/8

**Comment by laurendeaumatthieu** [comment]
Related errors:

- /usr/bin/ld: undefined reference to `__cudaRegisterTexture'
- /usr/bin/ld: undefined reference to `cudaUnbindTexture'
- /usr/bin/ld: undefined reference to `cudaBindTexture'
- /usr/bin/ld: undefined reference to `cudaBindTextureToArray'

**Comment by SimonRit** [comment]
Noting this link for future reference: https://developer.nvidia.com/blog/cuda-pro-tip-kepler-texture-objects-improve-performance-and-flexibility/

**Comment by SimonRit** [comment]
Fixed by #589.
