### ISSUE TITLE
Only one OutOfPlaneAngle in the RTK 3D circular projection geometry

### ISSUE THREAD

**Issue by piaomiao920** [RTKConsortium/RTK#556]
There is only one OutOfPlaneAngle in the geometry of rtk, and the actual system will have two OutofplaneAngles, does it have no effect?

**Comment by SimonRit** [comment]
The orientation of the detector is fully described by three angles: GantryAngle, OutOfPlaneAngle and InPlaneAngle. See documentation [here](http://www.openrtk.org/Doxygen/DocGeo3D.html). Please use the [mailing list,](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users) this is not a software issue.
