### ISSUE TITLE
How to use BoellaardScatterCorrectionImageFilter

### ISSUE THREAD

**Issue by jxhno1** [RTKConsortium/RTK#561]
How to decide the SetScatterToPrimaryRatio when using this filter?

**Comment by SimonRit** [comment]
This is more a question for the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users) than an issue. You can refer to the article, doi.org/10.1118/1.598066. That really depends on the scanner configuration (beam size, air gap, etc.). You can evaluate image quality for several values to estimate it. Please use the fix in #547 .

**Comment by jxhno1** [comment]
Thanks a lot， I am using the fix in#547 now。
