### ISSUE TITLE
Read Raw Data

### ISSUE THREAD

**Issue by navami123nair** [RTKConsortium/RTK#568]
Hi,
I am a beginner in using RTK. I would like to know if there is any specific format/method to read and display projection data stored in .raw format. This might be a silly question but please help me.
Thank you.

**Comment by SimonRit** [comment]
Please post your question on the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users), this is not a code issue. You can check the archives to see if the question has been addressed before, e.g. [here](https://www.creatis.insa-lyon.fr/pipermail/rtk-users/2023-January/001921.html).
