### ISSUE TITLE
Why SetTruncationCorrection(0.4) is not useful?

### ISSUE THREAD

**Issue by xem123** [RTKConsortium/RTK#584]
![image](https://github.com/RTKConsortium/RTK/assets/52185519/fba9058a-eb20-423a-b05e-a9d667660401)
I want to perform truncation correction on projection data, but why does the CT data obtained after using this function have no effect?

**Comment by xem123** [comment]
"I tried three parameters: 0, 0.2, and 1, but why is the effect of CT reconstruction exactly the same for all of them? Where can I find the source code for this function?"

**Comment by xem123** [comment]
![image](https://github.com/RTKConsortium/RTK/assets/52185519/0adababb-0f11-4e36-b846-698ce17c9eb2)
SetHannCutFrequency(0.46) and SetHannCutFrequencyY(0.46) can work effectively, but SetTruncationCorrection(0.8) doesn't have any effect.

**Comment by SimonRit** [comment]
Not an issue, please use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users) to clarify your question, e.g. by showing an example. Truncation correction has an effect if your projections are truncated.
