### ISSUE TITLE
How to output the image after truncation correction and ramp filtering?

### ISSUE THREAD

**Issue by xem123** [RTKConsortium/RTK#586]
![image](https://github.com/RTKConsortium/RTK/assets/52185519/32f112d5-ab83-4e4e-8a44-3d8d03822750)
hello！Lines 102, 103, and 104 set the truncation correction coefficients and filtering parameters, and the truncation correction, filtering, and CT reconstruction operations are performed in the update() function. How can I output the projection data after truncation correction? Do I need to modify the source code? And where in the source code is the truncation correction algorithm executed?
Thank you！

**Comment by SimonRit** [comment]
Please use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users), this is not an issue.
