### ISSUE TITLE
“itkRTK-5.2.lib” is not created

### ISSUE THREAD

**Issue by xem123** [RTKConsortium/RTK#588]
My question is same as https://github.com/RTKConsortium/RTK/issues/424. But I can't access the link in the picture, and it reports an error 404.How can I solve this problem?
Thanks!
![image](https://github.com/RTKConsortium/RTK/assets/52185519/045b9068-faed-495d-af5b-7f3ec49bb060)

**Comment by SimonRit** [comment]
The repository has been transferred to the RTKConsortium organization:
https://github.com/RTKConsortium/RTK/issues/419
