### ISSUE TITLE
Unable to successfully build the rtk library

### ISSUE THREAD

**Issue by xem123** [RTKConsortium/RTK#590]
I want to compile RTK. First, I downloaded the source code of ITK5.2.0 version, and then used cmake to compile ITK and RTK. My cmake configure is as follows, and the configure process can be completed normally. However, during building, an error occurred that ItkRtk-5.2.lib could not be found. What is the reason? Is it because my RTK_tag does not match ITK5.2.0? I have not been able to solve this problem, and I am in a hurry. Thank you!

cmake=3.29.2
visual studio 2017
ITK=5.2.0
moudle_RTK=on
Module_RTK_GIT_TAG=7a3282a4e5ba045ba3c00a4b51191fcb4a8bccae
fftw-3.3.5-dll64

![Uploading image.png…]()

**Comment by xem123** [comment]
After correctly configuring the path of cufftw.h, I can normally generate itkrtk.lib , which solves the above error; but now there is a new error, could you help me solve it?
![image](https://github.com/RTKConsortium/RTK/assets/52185519/5df29e3e-b1cb-4a43-8d4b-9833e022691a)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/457f71bb-a15d-403d-ac45-778ad116608e)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/428707ca-5790-477d-a895-906208d6a5a2)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/3f3fa71c-7a6a-43ad-b00a-22f2a2b46580)

**Comment by SimonRit** [comment]
Please used the latest release with the latest ITK release (v5.3.0) with
the latest RTK (master or v2.5.0). We do not support older version of ITK.
Simon
