### ISSUE TITLE
Unable to successfully build the rtk library

### ISSUE THREAD

**Issue by xem123** [RTKConsortium/RTK#592]
I want to compile RTK. First, I downloaded the source code of ITK5.3.0 version, and then used cmake to compile ITK and RTK. My cmake configure is as follows, and the configure process can be completed normally. However, I encountered an error during the build process, which reads as follows and seems to be related to the dcmtk library.Does the dcmtk library need to be downloaded separately? Or is it because there is a problem with my configuration? 
I have not been able to solve this problem, and I am in a hurry. Thank you!

cmake=3.20.1
visual studio 2017
ITK=5.3.0
moudle_RTK=on
Module_RTK_GIT_TAG=3f0aa3145d03b8cbc7c6d44bbfd03728b531909c
fftw-3.3.5-dll64

![image](https://github.com/RTKConsortium/RTK/assets/52185519/d2b8413e-20c1-4b86-9651-5194501d20ce)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/c97d5d22-ef07-434d-b26e-c6a6610f856a)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/abec00f0-8281-4a71-b79d-d71fc4c96364)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/0a00e325-e83a-4d7f-89ef-899385144d21)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/39f13c42-12cd-46e5-9e80-072e0b077000)

![image](https://github.com/RTKConsortium/RTK/assets/52185519/0aa0d2b6-918d-4344-8bfe-f5b2581b438a)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/ff846bdb-c1e4-45e3-9a9b-db9efeb7b3c9)

**Comment by xem123** [comment]
![image](https://github.com/RTKConsortium/RTK/assets/52185519/23385426-05a1-4dc2-9ea9-07f66a5e4f8a)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/d2be0175-2a9a-474f-9a37-f888ac23a250)

**Comment by SimonRit** [comment]
Have you tried to compile without  `Module_ITKDCMTK`? I also noticed that you ticked `ITK_USE_GPU` and `ITK_USE_CUFFTW` which are not required and might interfere with RTK (I haven't tried). It is also strange to have both `BUILD_SHARED_LIBS` and `BUILD_STATIC_LIBS` ticked, isn't it? In any case, unless you have a proven bug related to RTK, I would suggest to use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users).
