### ISSUE TITLE
Error C1001 An internal error has occurred in the compiler.

### ISSUE THREAD

**Issue by xem123** [RTKConsortium/RTK#593]
I have compiled itk and rtk and created a small example in visual studio, but I got an error，both in debug and release. What's the reason?The version I use is listed below：
cmake=3.20.1
visual studio 2017
ITK=5.3.0
moudle_RTK=on
Module_RTK_GIT_TAG=3f0aa3145d03b8cbc7c6d44bbfd03728b531909c
fftw-3.3.5-dll64
![image](https://github.com/RTKConsortium/RTK/assets/52185519/5848efde-6a7a-45de-bbbd-c194a6ef3969)

**Comment by SimonRit** [comment]
See https://github.com/InsightSoftwareConsortium/ITK/issues/4618#issuecomment-2081475913

**Comment by xem123** [comment]
![image](https://github.com/RTKConsortium/RTK/assets/52185519/6e98caa1-9994-4957-a766-6c2979974356)
![image](https://github.com/RTKConsortium/RTK/assets/52185519/f58dc846-06f3-4963-9a4f-ccd16eef88e9)
Hello, I want to compile the ITK library and the RTK library. I have successfully compiled using cmake, and completed build and install. However, when I place the compiled libraries into my project, I get compilation errors. What could be the cause?The version I use is listed below：
cmake=3.24.0
visual studio 2022
ITK=5.3.0
moudle_RTK=on
fftw-3.3.5-dll64
I am in a hurry, thank you!

**Comment by SimonRit** [comment]
In chinese it's hard to help. It seems to be an ITK error, not linked to RTK?
