### ISSUE TITLE
Cuda memory error when using Cuda forward projector

### ISSUE THREAD

**Issue by ObaidullahRahman** [RTKConsortium/RTK#594]
My image size is 1264x1356x1356=2324162304
Projection size: (slice/row, view, column)=(1456,145,1840)
My GPU has 80 GB memory.
When I use **CudaForwardProjectionImageFilter** I get memory error (please refer to the attachment).

Simon confirmed that in **line 115** of **rtkCudaUtilities.cu**, my image exceeds the predefined max size of the image.
Please increase the predefined max size for images.
(I'd like to be able to forward project 2000x2000x2000 image or as much as possible).
Thanks.

Best,
Obaid

<img width="602" alt="Screenshot 2024-04-24 at 8 34 20 PM" src="https://github.com/RTKConsortium/RTK/assets/36867277/e6554b6c-d682-4f0c-b41b-826685434683">

**Comment by SimonRit** [comment]
Dear Obaid,
Can you test the fix <https://github.com/RTKConsortium/RTK/pull/598> that I
have implemented? The new Python wheel can be downloaded from the CI if
you're logged in Github, at the bottom of the workflow page
<https://github.com/RTKConsortium/RTK/actions/runs/9051385855>.
Simon

**Comment by ObaidullahRahman** [comment]
Hi Simon,
I was able to install it. I also had to install the right itk (5.3.0) but that is beside the point.
I am getting the exact same error as before.
-Obaid
![Screenshot 2024-05-15 at 12 51 37 PM](https://github.com/RTKConsortium/RTK/assets/36867277/6705e230-cd34-4e9a-8802-14f63901abbc)

**Comment by SimonRit** [comment]
That does not seem to be the right installation. In a fresh environment, the requirement is ITK 5.4rc1, which can be installed with `pip install itk==5.4rc1`. Then make sure to install the package from the CI which does not seem to be what you have installed (rtkCudaUtilities.cu line 115 does not point to an exception).

**Comment by ObaidullahRahman** [comment]
When I install from the CI, this is error I get.
<img width="301" alt="Screenshot 2024-05-17 at 11 38 14 AM" src="https://github.com/RTKConsortium/RTK/assets/36867277/4a527e52-53a2-4af6-9b3e-e577e7e81afc">

**Comment by ObaidullahRahman** [comment]
> When I install from the CI, this is error I get. <img alt="Screenshot 2024-05-17 at 11 38 14 AM" width="301" src="https://private-user-images.githubusercontent.com/36867277/332456115-4a527e52-53a2-4af6-9b3e-e577e7e81afc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDA1NjgsIm5iZiI6MTcxNjMwMDI2OCwicGF0aCI6Ii8zNjg2NzI3Ny8zMzI0NTYxMTUtNGE1MjdlNTItNTNhMi00YWY2LTliM2UtZTU3N2U3ZTgxYWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE0MDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZDk1Y2FkZDU0MjczNDFhZDNhZDIwZmVkMjc5MzNkZDMxYTI1YjA1ZDZiZmI0Nzc1NDZhM2UwNGY4NzE4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o6Q3Oh2G9D7ZYEj6buW7m33_G-Lchfuj5jLU1Le1tfk">

That's why I have to downgrade to itk 5.3.0

**Comment by SimonRit** [comment]
If you downgrade, you cannot test the fix! Segmentation faults occur for me when I don't have a matching ITK version or if I do not install the correct linux version. There are two linux versions, 2014 for older versions and 2_28 for newer ones, have you tested both? BTW, ITK has released v5.4.0, you can test the new CudaCommon and RTK packages
https://github.com/RTKConsortium/ITKCudaCommon/actions/runs/9169210647
https://github.com/RTKConsortium/RTK/actions/runs/9169284466
Python 3.11 packages are not compiled yet but you can test one of the other Python versions.

**Comment by SimonRit** [comment]
The linux version depends on your OS version, see https://github.com/pypa/manylinux.

**Comment by ObaidullahRahman** [comment]
I was able to install this one:
<img width="931" alt="Screenshot 2024-05-22 at 5 32 03 PM" src="https://github.com/RTKConsortium/RTK/assets/36867277/44a72fba-d7e9-4722-9f94-cfb698a15668">

The itk that gets installed in indeed 5.4.0. But now I get a different error:
<img width="912" alt="Screenshot 2024-05-22 at 5 31 16 PM" src="https://github.com/RTKConsortium/RTK/assets/36867277/d7471e7f-a323-40c5-92e9-66bbd8536a43">

**Comment by SimonRit** [comment]
I'm surprised that you did not have that before. We do not ship the cuda libraries with the package, you have to install cuda 11.6 on your computer. You can have multiple versions of cuda on the same computer. For windows, you can add the cuda path like this: https://github.com/RTKConsortium/RTK/blob/master/examples/FirstReconstruction/FirstCudaReconstruction.py#L13-L14. For linux, add the cuda lib directory (containing libcudart.so.11.0 among others) to `LD_LIBRARY_PATH`. Note that you can also opt for Cuda 12.1 now.

**Comment by ObaidullahRahman** [comment]
I think I have cuda installed.
This is what **nvidia-smi** returns:
<img width="627" alt="Screenshot 2024-05-23 at 4 18 00 PM" src="https://github.com/RTKConsortium/RTK/assets/36867277/5ebf6264-145b-4a5d-946f-23a2ad30b7f7">

**Comment by SimonRit** [comment]
This just indicates the Cuda compability of your driver. Which OS are you using?
The package you have installed requires Cuda 11.6, ot Cuda 12.2. You may want to try the Cuda 12.1 version, I have experienced incompatibilities between Cuda 11.6 and a Cuda 12 driver.
