### ISSUE TITLE
Unable to compile simpleRTK

### ISSUE THREAD

**Issue by xem123** [RTKConsortium/RTK#605]
Hello, I want to use simpleRTK in Python. I saw on the official website that I need to compile the ITK library first, then the RTK library, and check the BUILD_SIMPLERTK option; but now the RTK library doesn't support separate compilation, right? Isn't it only possible to check the Module_RTK option when compiling ITK and then compile ITK and RTK together? Then how should I compile simpleRTK and use it in Python?
Thanks！
![image](https://github.com/RTKConsortium/RTK/assets/52185519/b9b7fef4-6cae-4361-aa86-7471d297a6ae)

**Comment by SimonRit** [comment]
See discourse answer: https://discourse.itk.org/t/unable-to-compile-simplertk/6723
