### ISSUE TITLE
Installation issue with pip

### ISSUE THREAD

**Issue by dwang6524** [RTKConsortium/RTK#607]
Hey, apologies for the simple question

I am trying to install RTK utilising pip on Mac M2 iOS 14.5, python 3.10.11. I use pip3 install itk-rtk and unfortuantely I get thrown the following error. I have also tried to install directly from the downloaded file with version RTK 2.4.1 with the exact same error.

Collecting itk-rtk
  Using cached itk-rtk-2.0.1.zip (2.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running egg_info
      creating /private/var/folders/z8/zhl6n59j48v1q68996xy65x00000gn/T/pip-pip-egg-info-l4z2warn/itk_rtk.egg-info
      writing /private/var/folders/z8/zhl6n59j48v1q68996xy65x00000gn/T/pip-pip-egg-info-l4z2warn/itk_rtk.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/z8/zhl6n59j48v1q68996xy65x00000gn/T/pip-pip-egg-info-l4z2warn/itk_rtk.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/z8/zhl6n59j48v1q68996xy65x00000gn/T/pip-pip-egg-info-l4z2warn/itk_rtk.egg-info/requires.txt
      writing top-level names to /private/var/folders/z8/zhl6n59j48v1q68996xy65x00000gn/T/pip-pip-egg-info-l4z2warn/itk_rtk.egg-info/top_level.txt
      writing manifest file '/private/var/folders/z8/zhl6n59j48v1q68996xy65x00000gn/T/pip-pip-egg-info-l4z2warn/itk_rtk.egg-info/SOURCES.txt'
      error: package directory 'itk' does not exist
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

Some help would be much appreciated!
Thank you!!

**Comment by SimonRit** [comment]
A few hours after posting this issue, I have released a new version of RTK, v2.6.0. You can try to pip install now?

**Comment by SimonRit** [comment]
Reopen if your issue is still relevant
