### ISSUE TITLE
why rtk::CudaFDKConeBeamReconstructionFilter's GetRampFilter()->SetTruncationCorrection() failed!

### ISSUE THREAD

**Issue by jxhno1** [RTKConsortium/RTK#609]
Try to use this filter as title described to do the trunction correction but found that when using a projection data size is 768x768 per frame, SetTruncationCorrection(0.0013) is ok, but SetTruncationCorrection(0.0026) failed! when using a projection data size is 1294x952 per frame, SetTruncationCorrection(0.0026) is ok, but SetTruncationCorrection(0.0013) failed! why this happened? FOV is the difference between this case, and the double num should be  calculated to follow some standard? 
Thank you for your help.

**Comment by SimonRit** [comment]
Can you please clarify what you mean by fail? 0.13% and 0.26% for the truncation correction, I typically use values closer to 1.

**Comment by jxhno1** [comment]
0.13% means I want to correct the ratio 1/768 and  0.26% means the ratio 2/768 for the truncation correction but it did matter among the two case.

**Comment by SimonRit** [comment]
Please clarify what you mean by "failed" and "it did matter".

**Comment by jxhno1** [comment]
Recon process is ok but final output  3d image is the zero value on all pixels. i said "it did matter" means  i wonder  why they both a parameter just using double as a input, but different in output image.
