### ISSUE TITLE
rtk::CudaIterativeFDKConeBeamReconstructionFilter memory error.

### ISSUE THREAD

**Issue by jxhno1** [RTKConsortium/RTK#623]
I used CudaIterativeFDKConeBeamReconstructionFilter to try a iter fdk case,  a error occur when the data size is 1294x952x600,
![image](https://github.com/user-attachments/assets/6d6e8246-1aed-4061-bfeb-9e0ba1800cf3)
but the data size 1294x952x300 is ok!
then I put the code on the 4090 card, as GPU memory is 24G, but the error still here.
then I try the cpu filter rtk::IterativeFDKConeBeamReconstructionFilter, data size 1294x952x600 run ok, so I think the CudaIterativeFDKConeBeamReconstructionFilter may have a bug in memory management?

**Comment by SimonRit** [comment]
Which RTK version are you using? There's been a bug fixed recently, it hasn't been released yet. See #612.

**Comment by jxhno1** [comment]
itkRTK：5.2 RTK：2.1




| |
jxhzk1314
|
|
***@***.***
|
---- Replied Message ----
| From | Simon ***@***.***> |
| Date | 10/14/2024 23:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [RTKConsortium/RTK] rtk::CudaIterativeFDKConeBeamReconstructionFilter memory error. (Issue #623) |

Which RTK version are you using? There's been a bug fixed recently, it hasn't been released yet. See #612.

**Comment by SimonRit** [comment]
Then there is another bug fix which explains it, #598. Please reopen if you still have the problem with the master version.

**Comment by jxhno1** [comment]
Thanks,I will try.




| |
jxhzk1314
|
|
***@***.***
|
---- Replied Message ----
| From | Simon ***@***.***> |
| Date | 10/16/2024 13:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [RTKConsortium/RTK] rtk::CudaIterativeFDKConeBeamReconstructionFilter memory error. (Issue #623) |

Then there is another bug fix which explains it, #598. Please reopen if you still have the problem with the master version.
