### ISSUE TITLE
How to save the projection data after first iteration when using CudaIterativeFDKConeBeamReconstructionFilter.

### ISSUE THREAD

**Issue by jxhno1** [RTKConsortium/RTK#624]

**Comment by SimonRit** [comment]
Please use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users) for user questions. From the command line, there is the `--output-every` option. The corresponding code is available in rtkMacro.h:
https://github.com/RTKConsortium/RTK/blob/master/include/rtkMacro.h#L201-L235

**Comment by jxhno1** [comment]
Thanks a lot！

**Comment by jxhno1** [comment]
I used the code below, run the process well done, but I can't find out the .mha file, where should I make the  change.Thank you!
![image](https://github.com/user-attachments/assets/f0bc3b04-d63b-4fd1-be11-22e5548ff0e7)
![image](https://github.com/user-attachments/assets/0049f281-e04f-4b4f-b8dc-165615bcbcf1)

**Comment by SimonRit** [comment]
Looks good to me, I don't know what could be missing... Maybe @acoussat knows?

**Comment by jxhno1** [comment]
@acoussat please give me some advice，thank you！
