### ISSUE TITLE
How to calculate lagcorrection ab factor in RTK I have projection data and airburst data

### ISSUE THREAD

**Issue by Y7NINE** [RTKConsortium/RTK#627]
![image](https://github.com/user-attachments/assets/2d80b907-8055-4cd9-b749-bfdf1154553f)
I want to ask how this coefficient is calculated and can the coefficient in the picture be used as a general purpose if I have the airburst data and the projection data

**Comment by SimonRit** [comment]
Please check the filter's reference, [Hsieh, Proceedings of SPIE, 2000]:
https://github.com/RTKConsortium/RTK/blob/master/include/rtkLagCorrectionImageFilter.h
You'd have to fit calibration data independently. Closing as this is not an issue but a user question which should go to the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users).
