### ISSUE TITLE
BackProjectionFilter python wrapping issue

### ISSUE THREAD

**Issue by vhamaide** [RTKConsortium/RTK#637]
Hi,

I noticed an issue with the Python wrapping when trying to set the `BackProjectionFilter` of `FDKConeBeamReconstructionFilter`.
Here is a minimal example:

```python
import itk
from itk import RTK as rtk

feldkamp = rtk.FDKConeBeamReconstructionFilter[rtk.Image[itk.F,3]].New()
feldkamp.SetBackProjectionFilter(feldkamp.GetBackProjectionFilter())
```

When running this, you get the error:
```
File k:\miniconda3\envs\itk-v2.6\lib\site-packages\itk\rtkFDKConeBeamReconstructionFilterPython.py:464, in rtkFDKConeBeamReconstructionFilterIF3.SetBackProjectionFilter(self, _arg)
    [455](file:///K:/opentps/miniconda3/envs/itk-v2.6/lib/site-packages/itk/rtkFDKConeBeamReconstructionFilterPython.py:455) def SetBackProjectionFilter(self, _arg):
[...]
--> [464](file:///K:/miniconda3/envs/itk-v2.6/lib/site-packages/itk/rtkFDKConeBeamReconstructionFilterPython.py:464)     return _rtkFDKConeBeamReconstructionFilterPython.rtkFDKConeBeamReconstructionFilterIF3_SetBackProjectionFilter(self, _arg)

TypeError: in method 'rtkFDKConeBeamReconstructionFilterIF3_SetBackProjectionFilter', argument 2 of type 'rtkFDKBackProjectionImageFilterIF3IF3_Pointer const'
```

This seems to be because `type(feldkamp.GetBackProjectionFilter()) == itk.rtkFDKBackProjectionImageFilterPython.rtkFDKBackProjectionImageFilterIF3IF3` is not a pointer.

In https://github.com/RTKConsortium/RTK/blob/master/applications/rtkfdk/rtkfdk.cxx#L177, you use `feldkamp->SetBackProjectionFilter(bp.GetPointer())` where bp is a `FDKWarpBackProjectionImageFilter`. Howerver, `GetPointer()` method is not accessible. How do we access the pointer in Python?

**Comment by SimonRit** [comment]
Thanks for the report. I have fixed the issue with #663, I believe the problem was that `itk::SmartPointer` should not be used if one wants to use the function in the wrapping.
