### ISSUE TITLE
Why it is different after using CudaIterativeFDKConeBeamReconstructionFilter and CudaFDKConeBeamReconstructionFilter

### ISSUE THREAD

**Issue by jxhno1** [RTKConsortium/RTK#638]
As I want to write a demo using CudaIterativeFDKConeBeamReconstructionFilter,  and I wonder why the Hu is  200 as it is 1000 when using  CudaFDKConeBeamReconstructionFilter.

**Comment by SimonRit** [comment]
By Hu you mean Hounsfiel Unit?

**Comment by jxhno1** [comment]
Yes, I used the same data but the CudaIterativeFDKConeBeamReconstructionFilter  case give me the Hounsfield Unit not close to the CudaFDKConeBeamReconstructionFilter one.

**Comment by SimonRit** [comment]
This is not what I observe on a simple example:
```bash
rtkprojectshepploganphantom -g g -o proj.mha --spacing 2
rtksimulatedgeometry -o g -n 36
rtkprojectshepploganphantom -g g -o proj.mha --spacing 2
rtkfdk -g g -p . -r ^proj.mha$ -o fdk.mha 
rtkiterativefdk -g g -p . -r ^proj.mha$ -o ifdk.mha
```
That must be something wrong with your data, not an RTK issue. Please provide a concrete demonstration or discuss your data on the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users).
