### ISSUE TITLE
External data: sha512 or md5

### ISSUE THREAD

**Issue by SimonRit** [RTKConsortium/RTK#641]
We currently have both sha512 and md5 files for external data.
See for example https://github.com/RTKConsortium/RTK/tree/master/test/Input/Bioscan.
Should we keep both? Any opinion @LucasGandel?

**Comment by SimonRit** [comment]
@LucasGandel, do you remember why we have both sha512 and md5?

**Comment by LucasGandel** [comment]
Not sure why, I think we always use sha512, but ITK had both at some point too. Now they moved to .cid : https://github.com/InsightSoftwareConsortium/ITK/issues/3760, maybe we should do the same

**Comment by SimonRit** [comment]
I think md5 can be removed, see #660. I have opened an issue for .cid, #661.
