### ISSUE TITLE
Update() causes Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LANGZHIZHEN** [RTKConsortium/RTK#651]
Thank you for developing RTK. One problem I have with RTK is that no matter what object calls Update(), a segment error is reported. My RTK is 2.6.0 and my ITK is 5.4.0.
`FOVFilterType = rtk.FieldOfViewImageFilter[CPUImageType, CPUImageType]
        fov = FOVFilterType.New()
        fov.SetInput(0, fdk.GetOutput())
        fov.SetProjectionsStack(projections)
        fov.SetGeometry(geometry)
        fov.Update()

        output_nrrd = os.path.join(self.DataRootDir, "SpineFromCuiGang-fov-cpu.nrrd")
        print(f"Writing output image to {output_nrrd}...")
        writer = itk.ImageFileWriter[CPUImageType].New()
        writer.SetFileName(output_nrrd)
        writer.SetInput(fov.GetOutput())
        writer.SetImageIO(itk.NrrdImageIO.New())
        writer.Update()`

**Comment by SimonRit** [comment]
Can your run [FirstReconstruction.py](https://github.com/SimonRit/RTK/blob/master/examples/FirstReconstruction/FirstReconstruction.py)? If not, there is something wrong with your installation, indicate your OS and Python version number to try reproducing the error.

**Comment by LANGZHIZHEN** [comment]
> Can your run [FirstReconstruction.py](https://github.com/SimonRit/RTK/blob/master/examples/FirstReconstruction/FirstReconstruction.py)? If not, there is something wrong with your installation, indicate your OS and Python version number to try reproducing the error.

Thank you very much for solving my problem. I got RTK down to 2.4 and ITK down to 5.3.0. But I have another problem, my input data is 200 * 512 * 512 image, geometry contains the projection matrix of each image, a total of 200 projection matrices. The result of my reconstruction is not a slice, but a side view. What is the cause of this?
![1](https://github.com/user-attachments/assets/2d52a123-039a-4f0a-9219-f0afd2f29c6b)

**Comment by LANGZHIZHEN** [comment]
> Can your run [FirstReconstruction.py](https://github.com/SimonRit/RTK/blob/master/examples/FirstReconstruction/FirstReconstruction.py)? If not, there is something wrong with your installation, indicate your OS and Python version number to try reproducing the error.

Thank you very much for solving my problem. I got RTK down to 2.4 and ITK down to 5.3.0. But I have another problem, my input data is 200 * 512 * 512 image, geometry contains the projection matrix of each image, a total of 200 projection matrices. The result of my reconstruction is not a slice, but a side view. What is the cause of this?
![1](https://github.com/user-attachments/assets/e72b6d9c-669f-42ec-beb2-c0377b4deecb)

**Comment by SimonRit** [comment]
Please use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users) or [ITK discourse](https://discourse.itk.org/), these are not code issues. I would need the geometry file to understand but I suspect a problem in the gantry angles or a short scan requiring [Parker](http://www.openrtk.org/Doxygen/classrtk_1_1ParkerShortScanImageFilter.html).

**Comment by LANGZHIZHEN** [comment]
> The result of my reconstruction is not a slice, but a side view. What is the cause of this?

<Projection>
    <GantryAngle>341.549556055667</GantryAngle>
    <SourceToIsocenterDistance>609.942829085676</SourceToIsocenterDistance>
    <SourceToDetectorDistance>1009.7465731124</SourceToDetectorDistance>
    <SourceOffsetX>-1.97616433848555</SourceOffsetX>
    <SourceOffsetY>7.26366136370983</SourceOffsetY>
    <ProjectionOffsetX>-153.734943225758</ProjectionOffsetX>
    <ProjectionOffsetY>-144.181181231914</ProjectionOffsetY>
    <InPlaneAngle>358.966707858677</InPlaneAngle>
    <OutOfPlaneAngle>0.386595294350592</OutOfPlaneAngle>
    <Matrix>
        -1005.75462481566    17.1847580637991   -175.445682858798   -94559.6041017832
        -63.0460918522241   -1010.58123745121    131.432245186592   -85038.2385729546
       -0.316477112957792 -0.00674730956154022   0.948576149177061   -609.942829085676
    </Matrix>
  </Projection>
  <Projection>
    <GantryAngle>340.494483992361</GantryAngle>
    <SourceToIsocenterDistance>610.053707296581</SourceToIsocenterDistance>
    <SourceToDetectorDistance>1009.9532506211</SourceToDetectorDistance>
    <SourceOffsetX>-1.37844181806165</SourceOffsetX>
    <SourceOffsetY>6.87782474869135</SourceOffsetY>
    <ProjectionOffsetX>-154.107468049441</ProjectionOffsetX>
    <ProjectionOffsetY>-143.92616467414</ProjectionOffsetY>
    <InPlaneAngle>358.972874448123</InPlaneAngle>
    <OutOfPlaneAngle>0.347071193257556</OutOfPlaneAngle>
    <Matrix>
        -1002.86995018297    17.1786942296269   -193.102251095857   -94565.0704591929
        -65.3749517647679   -1010.68594037261    130.335940096592   -85052.2513603692
       -0.333891482179037 -0.00605749801564417   0.942592056430605   -610.053707296581
    </Matrix>
  </Projection>
This is my geometry file

**Comment by LANGZHIZHEN** [comment]
`<Projection>
    <GantryAngle>341.549556055667</GantryAngle>
    <SourceToIsocenterDistance>609.942829085676</SourceToIsocenterDistance>
    <SourceToDetectorDistance>1009.7465731124</SourceToDetectorDistance>
    <SourceOffsetX>-1.97616433848555</SourceOffsetX>
    <SourceOffsetY>7.26366136370983</SourceOffsetY>
    <ProjectionOffsetX>-153.734943225758</ProjectionOffsetX>
    <ProjectionOffsetY>-144.181181231914</ProjectionOffsetY>
    <InPlaneAngle>358.966707858677</InPlaneAngle>
    <OutOfPlaneAngle>0.386595294350592</OutOfPlaneAngle>
    <Matrix>
        -1005.75462481566    17.1847580637991   -175.445682858798   -94559.6041017832
        -63.0460918522241   -1010.58123745121    131.432245186592   -85038.2385729546
       -0.316477112957792 -0.00674730956154022   0.948576149177061   -609.942829085676
    </Matrix>
  </Projection>
  <Projection>
    <GantryAngle>340.494483992361</GantryAngle>
    <SourceToIsocenterDistance>610.053707296581</SourceToIsocenterDistance>
    <SourceToDetectorDistance>1009.9532506211</SourceToDetectorDistance>
    <SourceOffsetX>-1.37844181806165</SourceOffsetX>
    <SourceOffsetY>6.87782474869135</SourceOffsetY>
    <ProjectionOffsetX>-154.107468049441</ProjectionOffsetX>
    <ProjectionOffsetY>-143.92616467414</ProjectionOffsetY>
    <InPlaneAngle>358.972874448123</InPlaneAngle>
    <OutOfPlaneAngle>0.347071193257556</OutOfPlaneAngle>
    <Matrix>
        -1002.86995018297    17.1786942296269   -193.102251095857   -94565.0704591929
        -65.3749517647679   -1010.68594037261    130.335940096592   -85052.2513603692
       -0.333891482179037 -0.00605749801564417   0.942592056430605   -610.053707296581
    </Matrix>
  </Projection>`
This is my geometry file

**Comment by SimonRit** [comment]
Please use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users) or [ITK discourse](https://discourse.itk.org/). This geometry file has only two projections next to each other, at 341.549556055667° and 340.494483992361, so the observed result is expected.
