### ISSUE TITLE
Help with CBCT reconstruction

### ISSUE THREAD

**Issue by LANGZHIZHEN** [RTKConsortium/RTK#653]
Hello, I have been reconstructing CBCT recently. The input data is 200 projection matrices, which are obtained by calculating 2D-3D coordinates through the Helix bucket, and 200 512*512 images. The output is 512 slices. I looked at FirstRectruction.py and I couldn't find where to add my image data to itk.Image[itk.F, 3], my image data is saved in np format. So how do I change the code

**Comment by SimonRit** [comment]
Not an RTK issue but a user issue, please use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users) or [ITK's discourse](https://discourse.itk.org/).
