### ISSUE TITLE
Readme or description?

### ISSUE THREAD

**Issue by peepo** [RTKConsortium/RTK#8]
Please could you add descriptions or Readme for each file?

rtkCudaBackProjectionImageFilter.cu

is it self evident, or immediately clear what the purpose is?

I am very interested by this project, and its imaging products, but even more interested by the process.

I found it from: 
http://cuda-programming.blogspot.co.uk/2013/02/texture-memory-in-cuda-what-is-texture.html

I'm also interested to write up tutorials about this processing.

**Comment by SimonRit** [comment]
Hi,
Please refer to the website http://www.openrtk.org, look at the Doxygen
documentation and if you can't find what you need, use the mailing list.
Simon
