### ISSUE TITLE
Too many ApplySupportmask in CG?

### ISSUE THREAD

**Issue by SimonRit** [RTKConsortium/RTK#85]
I have reviewed this code (for a new dev) and it feels that there are too many ApplySupportMask in the CG. It would be nice to check if we can reduce this. It would also be nice to let the mask filters appear in the documentation graph with dashed line to indicate that they are optional.

**Comment by cyrilmory** [comment]
ApplySupportmask has been replaced with proper filters. They now appear in the documentation graphs, though not with dashed lines
