### ISSUE TITLE
Memory leak in gengetopt usage?

### ISSUE THREAD

**Issue by BenChampion** [RTKConsortium/RTK#9]
The `GGO` macro in `rtkMacros.h` passes the `args_info` structure to a `cmdline_parser_*` function. I could not see any place where the `args_info` structure was freed (I was comparing it to the [gengetopt examples](http://www.gnu.org/software/gengetopt/gengetopt.html#Basic-Usage)).

When I used `valgrind -v --leak-check=full` with the `rtkfieldofview` program (I don't think there is anything special about `rtkfieldofview`, since `gengetopt` is used in many places), it seems to find memory that is allocated but not freed.

This is a very minor bug: I would not expect it to cause any real problems. (It looks like a tiny amount of memory!) Nevertheless I thought I would note it here.

**Comment by SimonRit** [comment]
Hi Ben,
Yes, you're right. I have currently removed gengetopt leaks from the
dynamic analysis because I feel they are very minor (as you pointed out).
If you want to do the same, you could use the RTK.supp file on the public
dashboard branch. We could also clean up the gengetopt memory... Do you
think it's worth it?
This is a good time because I have tried to do some work on memory clean up
in the past days.
Simon

**Comment by BenChampion** [comment]
Ahah, I was not aware of the `dashboard` branch and the `RTK.supp` file.

I will have a think about it. I wonder whether there might be a way to wrap the C malloc/free-like semantics in something that behaves more like a smart pointer, without breaking everything. Otherwise there is the effort and messiness of inserting a line at the end of every program to free the structure.

**Comment by BenChampion** [comment]
Hi Simon,
Turns out it's a little more complicated than I thought!

I've got a partial fix (see the second commit above - `c38d248`) that uses the fact that the `cmdline_parser_##ggo_filename##_free` function does not actually deallocate the whole structure, but just its string members (see the `gengetopt` documentation). I create an object containing a pointer to the `args_info` object whose destructor cleans up the `args_info` object by calling the `cmdline_parser_##ggo_filename##_free` function. Since this destructor will be automatically called before the `args_info` object is destroyed, it avoids having to insert a line at the end of each file calling the `cmdline_parser_##ggo_filename##_free` function. But quite hacky, perhaps.

However: in my testing, I tried manually calling the `cmdline_parser_##ggo_filename##_free` function, to compare its behaviour with my purported fix. It seems like although there are fewer memory leaks, they don't go away all together. Perhaps it is an issue with the `gengetopt` internals?

**Comment by SimonRit** [comment]
Hi,
Great! Why do you say it's hacky? It looks good to me. I have to check to which extent it works but I won't be able to do that until next week at best. I'll keep you posted but in any case, thanks a lot!
Simon

**Comment by BenChampion** [comment]
It just feels 'hacky' to use a destructor of one object to clean up another object that persists after the destructor returns. But it seems better than the other solutions I could think of (and interfacing C and C++ style memory management may just be ugly by nature!)

Things to look at when you do have a look at the code:
1) In my quick tests using rtkfieldofview, I got 20 memory leaks (`valgrind --leak-check=full`) with the old code, and 10 with the new code (and 10 with a manual call to the `*_free` function). I guess the exact numbers will depend on what arguments you supply.
2) Check that the build speed is acceptable -- I have some anecdotal experience with programs compiling a bit slower with the new code.
